### ISSUE TITLE
opus and HEVC support？

### ISSUE THREAD

**Issue by liyuxi** [ietf-wg-cellar/matroska-specification#100]
Please add opus and HEVC in CodecID spec

**Comment by liyuxi** [comment]
and DV,CinemaDNG,DNXHD，H.264,please add them in codec_specs.md

**Comment by dericed** [comment]
I did a receive crawl of the Matroska collection on archive.org, here's a histogram of the CodecID's used, maybe aren't referenced in the codec-mapping.md doc.

```
76209 A_AAC
   3 A_AAC/MPEG2/LC
   7 A_AAC/MPEG4/LC
  99 A_AAC/MPEG4/LC/SBR
   1 A_AAC/MPEG4/MAIN
15972 A_AC3
   9 A_AC3/BSID9
 594 A_DTS
  83 A_EAC3
1578 A_FLAC
 658 A_MPEG/L2
9980 A_MPEG/L3
  28 A_MS/ACM
25653 A_OPUS
   3 A_PCM/FLOAT/IEEE
 141 A_PCM/INT/LIT
   1 A_QUICKTIME/QDM2
 148 A_REAL/COOK
   3 A_TRUEHD
5586 A_VORBIS
   3 D_WEBVTT/SUBTITLES
1541 S_HDMV/PGS
21026 S_TEXT/ASS
 328 S_TEXT/SSA
7764 S_TEXT/UTF8
3797 S_VOBSUB
1590 V_MJPEG
  17 V_MPEG1
 203 V_MPEG2
 628 V_MPEG4/ISO/ASP
119340 V_MPEG4/ISO/AVC
   2 V_MPEG4/MS/V3
3065 V_MPEGH/ISO/HEVC
1604 V_MS/VFW/FOURCC
   1 V_QUICKTIME
   1 V_REAL/RV30
 147 V_REAL/RV40
  40 V_THEORA
 140 V_VP8
6240 V_VP9
```

**Comment by retokromer** [comment]
Thank you! Interesting indeed.

**Comment by mbunkus** [comment]
It'd probably be best to open one issue for each set of IDs that belong together but that aren't specified (e.g. `A_AAC`). Would make tracking the required changes easier. We also need to mark deprecated IDs as such (all the `A_AAC/…/…` and `A_AC3/…/…` specializations in favor of their respective simpler forms `A_AAC` and `A_AC3`).

> and DV,CinemaDNG,DNXHD，H.264,please add them in codec_specs.md

Additionally we should limit this issue to documenting existing codec mappings (such as Opus of H.264), not on creating new mappings (such as CinemaDNG).

**Comment by robUx4** [comment]
Closing this as all the existing Codec IDs are now covered.
