### ISSUE TITLE
Explain why ChapLanguage and ChapCountry are multiple

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#104]
And possibly make them unique.

**Comment by robUx4** [comment]
The idea was to name some chapters so user can see sections of a movie/album name. The same title can be used in various languages and translated/changed in some others. So the idea was to group together the ones using the same values rather than just repeating the `ChapterDisplay` over and over for each country/language. We should at least clarify that the list of languages are joined, same thing for the countries.

There's an issue for example if you put Canada in `ChapCountry` and a title in English. And another element with also Canada in `ChapCountry` and a title in French.

The multiple value should be for either the language or the country but not both at the same time to avoid possible cross reference mismatching...

Naming things should be better done with tags. Only the language is involved (which can target a specific country) and there's only possible value (forcing copies for each target countries/languages).

**Comment by mbunkus** [comment]
Making them non-multiple would potentially invalidate existing files, something I've never liked.

**Comment by hubblec4** [comment]
The multi language/country system confused me first, but now I think it is a good system. 
We should let it how it is.
In my chapterEditor is there for a full support implemented.

"
The multiple value should be for either the language or the country but not both at the same time to avoid possible cross reference mismatching...
"
+1 
If the language has multiple entries and the country also, then the language values should be prefered.

**Comment by retokromer** [comment]
It should be able to handle e.g. Swiss German and French for Switzerland and German (Hochdeutsch) for Germany and Austria. A common setting in TV productions.

**Comment by hubblec4** [comment]
Can the issue be closed?

**Comment by robUx4** [comment]
No since such explanation is still missing in the [Language Code section](https://github.com/ietf-wg-cellar/matroska-specification/blob/master/index_matroska.md#language-codes).

`ChapCountry` is particularly ill defined since the `ChapLanguage` may already have a country in it and it must be ignored if `ChapLanguageIETF` is set. We need to define how to use these 3 values and how to interepret them on playback.
