### ISSUE TITLE
many lines in code blocks exceed 72 chars

### ISSUE THREAD

**Issue by dericed** [ietf-wg-cellar/matroska-specification#140]
The lines below are from the make process with line numbers referring to the xml output. It seems the subtitle examples in particular use very long lines. Should move this out of a code block or break the lines up somehow.

WARNING: Output line (from source around line 549) is 83 characters; longer than 72.  Excess characters: '----------+':
  '|          |              |                    |----------------------------------+'

WARNING: Output line (from source around line 550) is 83 characters; longer than 72.  Excess characters: 'pString   |':
  '|          |              |                    | ChapterDisplay    | ChapString   |'

WARNING: Output line (from source around line 551) is 83 characters; longer than 72.  Excess characters: '----------|':
  '|          |              |                    |                   |--------------|'

WARNING: Output line (from source around line 552) is 83 characters; longer than 72.  Excess characters: 'pLanguage |':
  '|          |              |                    |                   | ChapLanguage |'

WARNING: Output line (from source around line 553) is 83 characters; longer than 72.  Excess characters: '----------+':
  '+---------------------------------------------------------------------------------+'

WARNING: Output line (from source around line 6988) is 196 characters; longer than 72.  Excess characters: 'ryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding':
  'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, TertiaryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding'

WARNING: Output line (from source around line 6989) is 87 characters; longer than 72.  Excess characters: ',2,2,5,5,30,0,0':
  'Style: Wolf main,Wolf_Rain,56,15724527,15724527,15724527,4144959,0,0,1,1,2,2,5,5,30,0,0'

WARNING: Output line (from source around line 6995) is 80 characters; longer than 72.  Excess characters: 'ct, Text':
  'Format: Marked, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'

WARNING: Output line (from source around line 6996) is 115 characters; longer than 72.  Excess characters: 'Et les enregistrements de ses ondes delta ?':
  'Dialogue: Marked=0,0:02:40.65,0:02:41.79,Wolf main,Cher,0000,0000,0000,,Et les enregistrements de ses ondes delta ?'

WARNING: Output line (from source around line 6997) is 87 characters; longer than 72.  Excess characters: ',Toujours rien.':
  'Dialogue: Marked=0,0:02:42.42,0:02:44.15,Wolf main,autre,0000,0000,0000,,Toujours rien.'

WARNING: Output line (from source around line 7027) is 76 characters; longer than 72.  Excess characters: '.wav':
  'Wav: 0, 128697,D:\Alex\Anime\- Fansub -\- TAFF -\Wolf's Rain\WR_-_02_Wav.wav'

WARNING: Output line (from source around line 7034) is 196 characters; longer than 72.  Excess characters: 'ryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding':
  'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, TertiaryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding'

WARNING: Output line (from source around line 7035) is 79 characters; longer than 72.  Excess characters: ',30,0,0':
  'Style: Default,Arial,20,65535,65535,65535,-2147483640,-1,0,1,3,0,2,30,30,30,0,0'

WARNING: Output line (from source around line 7036) is 84 characters; longer than 72.  Excess characters: '30,30,30,0,0':
  'Style: Titre_episode,Akbar,140,15724527,65535,65535,986895,-1,0,1,1,0,3,30,30,30,0,0'

WARNING: Output line (from source around line 7037) is 87 characters; longer than 72.  Excess characters: ',2,2,5,5,30,0,0':
  'Style: Wolf main,Wolf_Rain,56,15724527,15724527,15724527,4144959,0,0,1,1,2,2,5,5,30,0,0'

WARNING: Output line (from source around line 7040) is 80 characters; longer than 72.  Excess characters: 'ct, Text':
  'Format: Marked, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'

WARNING: Output line (from source around line 7041) is 115 characters; longer than 72.  Excess characters: 'Et les enregistrements de ses ondes delta ?':
  'Dialogue: Marked=0,0:02:40.65,0:02:41.79,Wolf main,Cher,0000,0000,0000,,Et les enregistrements de ses ondes delta ?'

WARNING: Output line (from source around line 7042) is 87 characters; longer than 72.  Excess characters: ',Toujours rien.':
  'Dialogue: Marked=0,0:02:42.42,0:02:44.15,Wolf main,autre,0000,0000,0000,,Toujours rien.'

WARNING: Output line (from source around line 7063) is 76 characters; longer than 72.  Excess characters: '.wav':
  'Wav: 0, 128697,D:\Alex\Anime\- Fansub -\- TAFF -\Wolf's Rain\WR_-_02_Wav.wav'

WARNING: Output line (from source around line 7070) is 196 characters; longer than 72.  Excess characters: 'ryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding':
  'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, TertiaryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding'

WARNING: Output line (from source around line 7071) is 79 characters; longer than 72.  Excess characters: ',30,0,0':
  'Style: Default,Arial,20,65535,65535,65535,-2147483640,-1,0,1,3,0,2,30,30,30,0,0'

WARNING: Output line (from source around line 7072) is 84 characters; longer than 72.  Excess characters: '30,30,30,0,0':
  'Style: Titre_episode,Akbar,140,15724527,65535,65535,986895,-1,0,1,1,0,3,30,30,30,0,0'

WARNING: Output line (from source around line 7073) is 87 characters; longer than 72.  Excess characters: ',2,2,5,5,30,0,0':
  'Style: Wolf main,Wolf_Rain,56,15724527,15724527,15724527,4144959,0,0,1,1,2,2,5,5,30,0,0'

WARNING: Output line (from source around line 7082) is 77 characters; longer than 72.  Excess characters: 'lta ?':
  '1,,Wolf main,Cher,0000,0000,0000,,Et les enregistrements de ses ondes delta ?'

WARNING: Output line (from source around line 7203) is 76 characters; longer than 72.  Excess characters: 'ngs.':
  'Example entry 3: That stuff to the right of the timestamps are cue settings.'

WARNING: Output line (from source around line 7286) is 76 characters; longer than 72.  Excess characters: 'ngs.':
  'Example entry 3: That stuff to the right of the timestamps are cue settings.'

**Comment by robUx4** [comment]
This is tricky. I'm trying to fix this but for example SSA/ASS defines lines with a certain amount of fields which apparently always have to be there (the spec is not very clear about that). So cutting/splitting them means it's not actually correct lines that can be parsed.

**Comment by dericed** [comment]
If we remove from code block then it would line wrap normally

**Comment by robUx4** [comment]
Yes but SSA/AAS is line based. That kinda defeats the purpose. If we move codec in another document that's an issue we can move for that document ;)
I think I fixed the other non SSA related issues.

**Comment by robUx4** [comment]
Seems fixed. I don't get any of these warnings.
Reopen if the issues emerge again. It may also be possible to track warnings in rfc build on GitHub to forbid such errors.
