### ISSUE TITLE
tagging: document how to use custom tags

### ISSUE THREAD

**Issue by dericed** [ietf-wg-cellar/matroska-specification#18]
I have a faint memory of reading somewhere that official mkv tags should be in all uppercase letters (and numbers) while anything else is an un-official tag. I like the part in the tags document about official tags but the use of un-official tags should be documented.

Referencing: https://github.com/dericed/matroska-specification/blob/gh-pages/tagging.md

**Comment by hubblec4** [comment]
The link for the referencing is dead.

I'm not sure if it's our task to describe how custom tags (actually TagName) can be used.
Sure the usage of the TagName element is not well documented.
But we have an official list with TagNames and all other Strings are valid.
How to use an unofficial TagNames is the work of the developer. For example the ROTATE TagName is an unofficial TagName but meets all criteria of an official TagName.

What the ROTATE does and what is necessary to use this TagName is not a Matroska task(or should be not).

**Comment by robUx4** [comment]
Looks the same as #49 which requires custom tags to start with an underscore.

**Comment by robUx4** [comment]
Custom tags start with an underscore as defined in #605. Closing.
