### ISSUE TITLE
support signedness clarifications for A_PCM/INT

### ISSUE THREAD

**Issue by dericed** [ietf-wg-cellar/matroska-specification#196]
See https://github.com/Matroska-Org/matroska-specification/pull/192 and https://github.com/Matroska-Org/matroska-specification/issues/142. Currently Matroska only describes default values for the signedness of PCM audio. I propose defining a method to clarify signedness, so for instance signed 8 bit or unsigned 24 bit could be supported.

**Comment by mbunkus** [comment]
Well, we still don't have a way for storing unsigned, correct? Not that I've ever come across it in the wild (sure, I can convert to it). Just saying.

**Comment by dericed** [comment]
Sorry, I accidentally closed this via the merge. Reopening.

Also in considering how to resolve this for `A_PCM/INT/BIG`, `A_PCM/INT/LIT`, and `A_PCM/FLOAT/IEEE` there is no defined initialisation. To address clarification of signedness we could add a new Element or perhaps define an optional initialisation for PCM audio, similar to kLinearPCMFormatFlagIsSignedInteger 
 of https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap3/qtff3.html#//apple_ref/doc/uid/TP40000939-CH205-BBCGGHJH.

**Comment by JeromeMartinez** [comment]
said in other words: `A_PCM/INT/LIT` is already defined as signed, so no change possible (no element which would change its definition), a new `A_PCM` could have a more general description and private part would contain flags (endianess, sign, float/int), or we define `A_PCM/UINT/*` for unsigned stuff.

**Comment by dericed** [comment]
`A_PCM/INT/LIT` is not defined as signed, but the signedness is conditional based on the bit depth. For instance:
`ffmpeg -f lavfi -i sine -c:a pcm_u8 -t 1 test.mka`
vs
`ffmpeg -f lavfi -i sine -c:a pcm_s32le -t 1 test.mka`
both use `A_PCM/INT/LIT`.

**Comment by JeromeMartinez** [comment]
Argh, sorry, I read too quickly (and understood from Moritz comment that we don't have unsigned) , it is indicated in current spec too.
OK, so now IIUC we don't have **signed** for 8-bit, right? In theory unsigned 16/24-bit is possible but never found such content.
AIFF can transport signed 8-bit (FFmpeg can create such file), so should we permit that?
As `A_PCM/INT/LIT` already defined sign, IMO we can't override that with a new element, we need another "Codec" (`A_PCM`?) saying that definition  (endianess, sign, float/int) is in private metadata, if we really need to support signed 8-bit.
Else IMO definition is good as is.
