### ISSUE TITLE
consider Chapter cruft

### ISSUE THREAD

**Issue by dericed** [ietf-wg-cellar/matroska-specification#203]
I have a sample set of 131,505 real world Matroska files that have been analyzed. Of these 14,746 have a Chapters Element (11.2%). Considering the Chapters section alone, here are the Elements that are unused in the sample set (presuming that MediaInfoLib is parsing for these elements correctly).

```
ChapterTrack
ChapterTrackNumber
ChapProcessPrivate
ChapProcessCommand
ChapProcessTime
ChapProcessData
```

**Comment by hubblec4** [comment]
I think this elements was implemented for the Matroska DVD Menu system.(?) 
The element ChapProcessData is used by the Matroska Native menu. (I have working samples).

ChapterTrackNumber is a very interessting element, cause it can be used as an aquivalant to the TRACKSETEX (Halli).

For me is the element ChapterTrack element (and all sub-elements) ok, and maybe we need all elements for the "new Matroska menu".

**Comment by hubblec4** [comment]
Hey @dericed, 
in your sample set, exists an mkv with the chapter element `ChapterSegmentEditionUID`?

I have never seen this element in use and I don't understand right the usage of it.
I think this element belongs to the DVD-menu system. Maybe we don't need it, when we remove the DVD-menu.

**Comment by robUx4** [comment]
Yes most of these elements exist for menu and codec chapters which are currently unused.

**Comment by hubblec4** [comment]
@robUx4 
Not all elements are unused.
ChapProcessTime and ChapProcessData are used in the Native Matroska menu(with GotoAndPlay) and  it works in VLC. Good job Steve, I like this feature.

**Comment by robUx4** [comment]
We decided to keep the chapter codecs in the main spec for now.
The `ChapterTrack` elements are considered to be moved out of the spec in #461.

Closing this in favor of #461.

**Comment by hubblec4** [comment]
Yes, can be closed.
