### ISSUE TITLE
Only one Edition with EditionFlagHidden Flag set to true

### ISSUE THREAD

**Issue by hubblec4** [ietf-wg-cellar/matroska-specification#206]
If exists one Edition only and the Edition is hidden,
what is the correct usage?

Practice:
LAV Splitter ignores the Hidden-Flag and show all chapters.

My first thought:
We could say this is ok and describe it in the specs.

But on the other hand I prefer all chapters should not be visible.
The Edition is used and if the Ordered Flag is set to true then a virtual timeline must be created but without showing the chapter marks.

**Comment by robUx4** [comment]
Ref. #461 this should be set as work for this new document.

**Comment by robUx4** [comment]
`EditionFlagHidden` is now marked as enabled by control tracks only.
