### ISSUE TITLE
remove matroska.org direct links from ebml_matroska.xml

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#233]
Ideally it would link to the section of the RFC.

**Comment by mcr** [comment]
Replace them with xref target=# links within the document.

**Comment by robUx4** [comment]
Related to #380 

- the links to the chapter pages should reference sections in the same document
- the links to codec and tag pages should reference the IETF drafts

**Comment by robUx4** [comment]
Apart from a commented out `TimestampScaleDenominator` element in `ebml_matroska.xml` and the email addresses, we no longer use matroska.org anywhere in the specs.
