### ISSUE TITLE
Remove Control Track from the working docs

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#234]
It should not go in the RFC for now as it's not used anywhere (unlike Chapter codec/menu there is no code to handle it anywhere).

**Comment by hubblec4** [comment]
The Control Track is a part of Chapter codec/ Matroska menu and your code in VLC is today the only one which deals a bit with this topic.

I think for the normal working docs it is not necessary and could removed.

But Steve, do not stop working on VLC's Matroska demuxer, it is the best chance for the moment to get Matroska menu/Control Track working.

**Comment by robUx4** [comment]
We might move that to an appendix for now.

**Comment by robUx4** [comment]
Duplicate of #456
