### ISSUE TITLE
ChapterSegmentEditionUID

### ISSUE THREAD

**Issue by hubblec4** [ietf-wg-cellar/matroska-specification#267]
This Matroska element is not completely clear to me, so I wanted to ask for some info.

The current description says:
>The EditionUID to play from the segment linked in ChapterSegmentUID.

The meaning of this sentence is easy. An edition should be played from the linked segment.
But this is not "possible" in my eyes.
Before we can use the `ChapterSegmentEditionUID` element we have to set the `EditionFlagOrdered Flag` to true. That means we have to specify a chapter start time and an end time(current state of the chapter specs) and we must set a `ChapterSegmentUID` (to link to another Matroska segment/file).

The linked chapter duration is now used in the virtual timeline.
An edition can have more then one chapter and so it is unclear to me how I can specify this, so that an edition is played. The duration of a linked edition can/is different to the linked chapter duration.
Such a case is when the linked edition is also Ordered-constructed and the timestamps not consecutive.

I can imagine me that Matroska DVD menu system uses this `ChapterSegmentEditionUID` element,
because the rules for the end timestamps are different to "normal" ordered chapters/edtions.
But I don't found this element in the output files of DVDMenuXtractor.

Is this element anywhere used?

**Comment by hubblec4** [comment]
Here a great info. This element is used in mpv and it works in my first tests (but I don't know how exactly).
I will make more tests.
https://github.com/mpv-player/mpv/pull/258

**Comment by robUx4** [comment]
`ChapterSegmentEditionUID` is paired with `ChapterSegmentUID`. It's unfortunate they are not combined within a Master element.

We can probably refine a bit more the explanations on ordered chapters with segment linking.

**Comment by hubblec4** [comment]
> We can probably refine a bit more the explanations on ordered chapters with segment linking.
Yes, I will try to do this.
