### ISSUE TITLE
ChapLanguageIETF

### ISSUE THREAD

**Issue by hubblec4** [ietf-wg-cellar/matroska-specification#289]
I see Mosu has added the ChapLanguageIETF element in the old Matroska specs page.
This element can not used multiple times like the normal ChapLanguage element.

To set more then one language per chapter name is in my eyes very important. I have many chapter samples with 2 or more languages and some chapter names are identical for all languages. In this cases exists one chapter display only with multiple languages.

Is there a reason why ChapLanguageIETF can be used one time only?

**Comment by dericed** [comment]
It was probably a part of copy/paste from other language elements such as TagLanguage which are set to maxOccurs=1. I checked the wg email and pull request discussions but couldn't find a reason to limit ChapLanguageIETF to not recur.
