### ISSUE TITLE
EditionName

### ISSUE THREAD

**Issue by hubblec4** [ietf-wg-cellar/matroska-specification#300]
To set a name for an edition you have to use Tags and there are you can set more as the name for example TargetTypeValue and TargetType. But for me are other values as the name total uninteresting.
When you delete the Tags all edition names are lost.
A parser must search the Tags additional to get the edition name(s).

It would be great to add the EditionName element.

**Comment by robUx4** [comment]
So something similar to `ChapterDisplay` but for editions. That makes sense. Or rather no reason to have one and not the other.

**Comment by hubblec4** [comment]
EditionDisplay sounds interesting. Is this not to much for a name only?
But on the other hand....
In a Display we can have multiple names with multiple languages, countries and languagesIETF.
All countries and languages from the EditionDisplay could be used for all `ChapterDisplays` and could be omitted there, which reduce the file size. (I have mkv's with more then 1000 chapters)
