### ISSUE TITLE
EditionDuration

### ISSUE THREAD

**Issue by hubblec4** [ietf-wg-cellar/matroska-specification#301]
In Matroska exists many Duration elements but not for an edition.
The duration of an edition is in some cases not the file or video duration.

On the StarTrek TNG Blu-rays are episodes with a play duration of 45min:30sec (says the mpls and each player use this duration) but the video duration is 45min:32sec and when you play this m2ts directly then it play 45min:32sec.

The EditionDuration is implemented in my chapterEditor and is used to create the last end timestamp for an ordered chapter.

**Comment by robUx4** [comment]
This doesn't seem right (and we are not M2TS). Either the edition is unordered and the duration is exactly the one of the `Segment`. If it's ordered it _may_ usefull to advertise it, but then if you edit you need to recompute it. Plus a reader that would handle ordered chapters needs to read all of them so will know the actual duration anyway.

It's usually a bad idea to store twice the same information in different way.

**Comment by hubblec4** [comment]
When I merge such m2ts to an mkv it plays 45min:32sec(without ordered chapters). But this is not the original duration of the mpls/title and a user maybe don't understand why it plays 2 sec longer.

I think you know that the SegmentInfo Duration has always the longest duration of all tracks, and this is mostly an audio track and this is a wrong input to create a correct ordered edition.

The EditionDuration must not be the entire Segment Duration!
I try to explain it.
I have a Tutorial video which have 5 parts. A opening part which is used in all editions, this means all editions start from timestamp 0.

The first edition use part 1+2. Part 2 has an end time of 10min in the mkv.
The second edition use part 1+3. Part 3 has an end time of 30min in the mkv.
and so on...

Each end time of a part could be used as EditionDuration...
but I know what you mean when ordered chapters are used, the EditionDuration don't match to the sum of all chapter-durations.
EditionDuration is maybe not correct. EditionEndTime is maybe be better.

Mosu has also added an automatic to generate chapter end timestamps in his Chapter Editor.
I use such an automatic for a long time in chapterEditor(cE) and for the last end timestamp there is no information. I believe Mosu's end time generator lets this value blank/ or use the start time(chapter duration is now 0, not used).
With cE's internal EditionDuration I can set an end timestamp for the last ordered chapter.

EditionEndTime sound really better...
If the EditionEndTime is set (greater as 0) a player could stop playing even if the edition is not ordered.
The m2ts.mkv plays then exactly 45min:30sec like the mpls says or any other Blu-ray player.

**Comment by hubblec4** [comment]
Now I understand why the m2ts duration is longer as the mpls duration.
There is an mpls for playing the episode separate and 45min:30sec is used but in another mpls which plays all episodes seamlessly, the 2 extra seconds are used to have "a black pause" between the episodes.

The In_Time of both mpls is the same but the Out_Time is different.

The mpls-sample is one case only, there are other cases where and EditionEndTime is used/useful.

**Comment by hubblec4** [comment]
For the moment I agree with the "wontfix" label. It's not the right time to implement this feature.

The EditionEndTime is also not enough after thinking about this topic.
Maybe I need an EditionTimeStart and EditionTimeEnd.
