### ISSUE TITLE
Reference deprecated IDs separately

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#305]
These elements have nothing to do in the main spec. On top of that the spec is not available from DivX anymore.

They should be an extension, expect the existing files using this (trick play) feature don't have the EBML extension header in them.

**Comment by robUx4** [comment]
Also the `divx` attribute we use in the XML Schema is not a valid attribute to define EBML.

**Comment by hubblec4** [comment]
I have never seen a file with DivX elements. I agree with the removal.

**Comment by mkver** [comment]
I also agree with the removal and have two more questions: Were these elements just used by DivX without consulting the Matroska guys? And if these elements are removed, does this mean that their `Element ID` will be available again and might be reused for something completely different? (The DivX guys used one octet `Element IDs` for elements that only exist once in a `TrackEntry` of a track using these DivX extensions. What a waste!)

**Comment by dericed** [comment]
https://github.com/cellar-wg/matroska-specification/pull/325 is related to this issue as it moves the divx attributes however the related elements still are there.

**Comment by robUx4** [comment]
The DivX elements were only created by DivX tools AFAIK and only handled by their player(s). They put the documentation online but never consulted with us.
Now the specification is gone.

IMO the IDs should not be reused to maintain compatiblity with such files (if the same ID was used in the future with a different type or different meaning it might lead to serious issues). Again, the IDs alone could be found in different parts of the file and never really collide. So IMO we should keep track of the path theses IDs were used in the past and not reuse them there. We can keep the elements in the spec and set `maxver=0` meaning they can never be used.

**Comment by dericed** [comment]
In the EBML spec we say that maxver MUST >= than minver. In some cases like 'SimpleBlock' there is a minver=2. IMHO to update that to say minver=2 and maxver=0 is invalid. I'd suggest that use maxver=2 in this case and perhaps add a comment to say that they are not recommended.

**Comment by robUx4** [comment]
Given there are not official we could say both `minver=0` and `maxver=0`. A validator will consider existing files invalid. But the elements would still be known and documented.

**Comment by dericed** [comment]
Does that imply that there is a Matroska version 0?

**Comment by robUx4** [comment]
This is already how we marked elements many elements as existing but should not be used (`BlockVirtual`, `FrameNumber`, `EncryptedBlock`, etc).

Also all the DivX specific elements already have `minver=0` and `maxver=0` so we don't even need to do anything special.

**Comment by robUx4** [comment]
The elements are already marked with `maxver="0"` and the divx extension is set.
We can keep it in `ebml_matroska.xml` for tools that generate code from it. The elements should be stripped from the RFC specifications.

**Comment by robUx4** [comment]
@dericed , @mbunkus , @mcr any opinion on having a part of the RFC (maybe an annex) where we list old IDs that should not be used (ie marked as maxver="0") with the description of what they used to do. This is not normative (unlike the other elements) but to avoid overlapping when adding new elements it's good to avoid these.

In addition to maxver="0" there's also `0x44B4` which was a bug in libavformat, and maybe other code, where it was used instead of `0x4484` (`SimpleTag\TagDefault`). It should also be part of the IDs not to use if possible.

**Comment by mbunkus** [comment]
I'm all in favor of having a list of IDs that shouldn't be used. I'm unsure, though, if such a list should be part of the specs as that list might grow (e.g. due to similar bugs such as the `0x44B4` / `0x4484` but in libavformat). Maybe implementing a registry for it would be better?

**Comment by mcr** [comment]
> @dericed , @mbunkus , @mcr any opinion on having a part of the RFC (maybe an annex) where we list old IDs that should not be used

Yes, they would go into the appropriate IANA table/registry marked historic, and the description of them could be in an appendix.
This is entirely appropriate, as those IDs might be out there and people want to know how to decode them.

**Comment by SpencerDawkins** [comment]
If I might offer what I hope is a friendly amendment ... 

This kind of material is fine in IANA registries, but I'd suggest considering a separate "Implementer's Guide" document for the descriptions of what has been deprecated and why. Other protocols that have this kind of thing are TCP (at https://tools.ietf.org/html/rfc7414) and SIP (at https://tools.ietf.org/html/rfc5411). 

Putting this in an informative appendix makes it less likely that someone would trip over it by accident, and just adds material to specifications that already aren't particularly small. 

Perhaps we can chat about this in our next virtual interim, when we're reviewing issues.
