### ISSUE TITLE
Add a way to identify tracks for the hearing impaired

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#313]
Typically subtitles. It could also be audio tracks containing Audio Description.

It can currently be stored as tags, but it's needed to select the proper tracks when playing so it should really be found in the Tracks.

**Comment by hubblec4** [comment]
subtitles -> hearing impaired
audio -> visually impaired

We could add two new Matroska elements?

**Comment by robUx4** [comment]
Fixed by #447
