### ISSUE TITLE
Will codec spec update future?

### ISSUE THREAD

**Issue by liyuxi** [ietf-wg-cellar/matroska-specification#316]

**Comment by dericed** [comment]
Yes, we periodically make a new RFC output from the content of this repository and post it at https://datatracker.ietf.org/wg/cellar/documents/. Is there a particular codec mapping you're interested in?

**Comment by liyuxi** [comment]
> 是的，我们会定期从此存储库的内容中创建一个新的RFC输出，并将其发布在[https://datatracker.ietf.org/wg/cellar/documents/上](https://datatracker.ietf.org/wg/cellar/documents/)。是否有您感兴趣的特定编解码器映射？

H.264,H.265,EAC-3 are all not include in the latest draft-ietf-cellar-codec memo

**Comment by liyuxi** [comment]
> 是的，我们会定期从此存储库的内容中创建一个新的RFC输出，并将其发布在[https://datatracker.ietf.org/wg/cellar/documents/上](https://datatracker.ietf.org/wg/cellar/documents/)。是否有您感兴趣的特定编解码器映射？

opus and av1,too.They are widely used in Matroska（I think av1 will）

**Comment by JeromeMartinez** [comment]
> EAC-3

This one is supported ("A_AC3/BSID10" because E-AC-3 uses a different "bsid" but the frame header is same).
There is an open issue #230 about if we should accept "A_EAC3" Codec ID, [discussion](https://github.com/cellar-wg/matroska-specification/issues/230#issuecomment-394254675) is more to accept it in a demuxer but not recommend it officially.

**Comment by liyuxi** [comment]
> > EAC-3
> 
> 支持这一个（“A_AC3 / BSID10”，因为E-AC-3使用不同的“bsid”，但帧头相同）。关于我们是否应该接受“A_EAC3”编解码器ID，
> 有一个未解决的问题[＃230](https://github.com/cellar-wg/matroska-specification/issues/230)，[讨论](https://github.com/cellar-wg/matroska-specification/issues/230#issuecomment-394254675)更多是在分离器中接受它但不正式推荐它。

Except eac3，the other are all progressing slowly

**Comment by dericed** [comment]
The codec spec document had a release point and was updated at https://datatracker.ietf.org/doc/draft-ietf-cellar-codec/. From the wording of the issue I'm uncertain if now it's closed or if there is some other specific goal to close this issue.

**Comment by robUx4** [comment]
I think the general idea is that the codec definitions for the widely used codecs is lacking and needs some update. It will come but likely after the main Matroska spec is well advanced. Of course, Pull Requests are welcome.

**Comment by mcr** [comment]
Translation of above: "This one is supported ("A_AC3 / BSID10" because E-AC-3 uses a different "bsid" but the headers are the same). Regarding whether we should accept the "A_EAC3" codec ID, there is an unresolved issue #230, and more is discussed in the splitter but it is not officially recommended."

**Comment by liyuxi** [comment]
> The codec spec document had a release point and was updated at https://datatracker.ietf.org/doc/draft-ietf-cellar-codec/. From the wording of the issue I'm uncertain if now it's closed or if there is some other specific goal to close this issue.

A long time passed，the codec of key have not included in the spec，H.264，H.265 support has been a de-facto standard for a long time

**Comment by robUx4** [comment]
This is a lot of work to finalize all these documents. We concentrated on the EBML document lately so we can be done with it. Next is the main/general Matroska document. So codecs will have to wait. But if you can spend some time updating the document and submit some pull requests, it's very welcome.

**Comment by mbunkus** [comment]
AV1: We already have a file for that, but it isn't included in the codec mapping spec yet. Probably an oversight. I'll open a separate issue for that.

**Comment by robUx4** [comment]
It's not an oversight. It's not supposed to be a RFC (for now) but it is the reference document on how to put AV1 into WebM and Matroska. If it's a problem to have non-RFC documents in this repo, I can move it somewhere else.

**Comment by mbunkus** [comment]
AV1: It's not really a problem, just a tad confusing and unclear, that's all. As long as it isn't mentioned anywhere people will rightfully continue to assume we don't have specs for it.

**Comment by robUx4** [comment]
The discussions to edit this document happen outside of IETF. So I think it should be moved. But you're right we should also make it more visible. Not sure if the new `infrastructure` repo would fit but that's probably the closest (where we can properly version it).

**Comment by mbunkus** [comment]
That repo would be a good place for the time being.

**Comment by robUx4** [comment]
Closing as all codecs mentioned are part of the latest version.
