### ISSUE TITLE
ChapterTimeEnd should not be marked as informational

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#322]
See the table in `EditionFlagOrdered` that says it might be.

**Comment by robUx4** [comment]
Needed for #318

**Comment by hubblec4** [comment]
When we allow a ChapterTimeEnd in Basic chapter(only ChapterTimeStart is used) than we must describe a special cases. It will be to complicated.

ChapterContentType is a new feature an should be available in ordered chapters only.

Basic chapters should stay basic/simple.

**Comment by robUx4** [comment]
IMO the `ChapterContentType` from #318 doesn't need ordered chapters. Ordered chapters should only be used for reordering of content or multiple editions on the same file. Most players don't support the feature and it's not expect they do in the foreseeable future.

The `EditionFlagOrdered` table, which is a bit confusing to read, doesn't mean that `ChapterTimeEnd` is forbidden or "informational" (that term is not written). So IMO we don't need any change regarding the `ChapterTimeEnd`.

**Comment by robUx4** [comment]
Fixed by #440 which does mention ChapterTimeEnd as ordered chapters specific anymore.
