### ISSUE TITLE
document image flipping

### ISSUE THREAD

**Issue by dericed** [ietf-wg-cellar/matroska-specification#327]
see https://github.com/cellar-wg/matroska-specification/pull/326#issuecomment-511088866

**Comment by robUx4** [comment]
That would be done through `ProjectionPoseYaw` of 180 degree, similar to how `ProjectionPoseRoll` can be used for rotation in #326

**Comment by robUx4** [comment]
Actually vertical flipping would be a `ProjectionPosePitch` of 180. Horizontal flipping would be a `ProjectionPoseYaw` of 180.
