### ISSUE TITLE
Mark which elements (UIDs) need to be preserved when remuxing

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#370]
`TrackUID` is already documented as such
```This SHOULD be kept the same when making a direct stream copy of the Track to another file.```

I think a lot of IDs that are referenced in chapters, tags, attachments also need to be preserved. So we need to make sure they are marked as such (maybe an extension in our generic XML file).

**Comment by hubblec4** [comment]
Yes, some UID's should/must be kept when making a direct stream copy.

For chapters I think there is no automatic which generates new UID's when remuxing. I guess this UID's are always kept.

TrackUID's or AttachmentUID's could be referenced in Chapters and/or Tags for example.
