### ISSUE TITLE
Labels not readable

### ISSUE THREAD

**Issue by hubblec4** [ietf-wg-cellar/matroska-specification#445]
You have changed some colors of the Labels, and now it is not possible to read the caption of some Labels.

**Comment by robUx4** [comment]
What labels are unreadable and what color do you suggest?

**Comment by hubblec4** [comment]
What was wrong with the old colors? Could you restore them?

**Comment by robUx4** [comment]
It's possible to change colors, but without knowing which is wrong, the same issue will repeat itself anway.

**Comment by hubblec4** [comment]
spec main
clarifications
format addition
bug -> is readable but with pain in the eyes

**Comment by robUx4** [comment]
OK so it's white text on dark background. This is odd because they are some with the highest contrast between the text and the background. For example `format extension` is black on not very like background so it blends a little too much and is harder to read to me.

I'll change to light backgrounds, which will trigger the text to be in black. But I don't think it's normal you have a hard time reading white text on very dark background (`spec_main` uses https://www.color-hex.com/color/023b75 for example). Especially as GitHub now has a dark background mode as well (so white text). I wonder how all these colors look in dark mode BTW. I hope they thought about that.

**Comment by hubblec4** [comment]
All Labels are readable now. Thanks

**Comment by robUx4** [comment]
New report
> the new label "build+system" is not readable, I don't want open a new issue.

It's [new label](https://github.com/ietf-wg-cellar/matroska-specification/issues?q=label%3A%22build+system%22+is%3Aclosed).

What are you viewing conditions that make it hard to read ? I don't have an exceptional view and yet I can see the labels just fine. Are you sure your screen contrast is not messed up ? It seems you only have an issue with light text on dark background which is what most people use in dark mode nowadays.

There aren't a ton of available colors that are easily distinguishable from each other for labels. I'd rather be able to use all of them if we can solve this issue.

**Comment by robUx4** [comment]
If you look at the [list of labels](https://github.com/ietf-wg-cellar/matroska-specification/labels) IMO there are some that are hard to read but not that one.

- av1-mapping
- discussion
- format extension

There are dark text on dark background. I'd rather fix these ones although I can still read them without trying too hard.

**Comment by hubblec4** [comment]
Here a screenshot to show what I see.
![Labels](https://user-images.githubusercontent.com/25957077/111072832-9b69b600-84dc-11eb-9118-6223ef518cb9.png)


I use mostly standard/default settings for all my devices.

**Comment by robUx4** [comment]
Strange, this is not how it's supposed to look like, at least not how I see it.

![gh-labels](https://user-images.githubusercontent.com/657717/111073075-978a6380-84dd-11eb-85ba-1135f2eb6beb.png)

What browser/OS are you using ? Are you using a special Github theme in https://github.com/settings/appearance ? I'm using Default Light.

**Comment by mbunkus** [comment]
I'm slightly confused why the "build system" label is black-on-blue for you. Here's how it looks in Chrome, Vivaldi, Firefox & the old Internet Explorer for me:

![2021-03-14 15_55_00-Issues · ietf-wg-cellar_matroska-specification · GitHub — Mozilla Firefox](https://user-images.githubusercontent.com/414282/111073106-bee13080-84dd-11eb-9cf8-c21c050fa0a8.png)

Are you using any kind of browser extension that might affect the display? Custom CSS?

**Comment by robUx4** [comment]
![gh-dark](https://user-images.githubusercontent.com/657717/111073183-0b2c7080-84de-11eb-86ac-381012c9c2a1.png)

Even with Default dark it looks OK to me.

**Comment by robUx4** [comment]
I'm using Firefox. I tried in Edge (Chrome) and it looks more or less the same as my Firefox.

**Comment by mbunkus** [comment]
BTW, as an explanation for @hubblec4 , we can only configure the background color of the labels. Github automatically selects an appropriate foreground color.

**Comment by hubblec4** [comment]
I'm using Win7 (classic view) with Firefox64-portable and/or Waterfox.

**Comment by hubblec4** [comment]
> Are you using any kind of browser extension that might affect the display? Custom CSS?

No extensions or other things installed.

**Comment by hubblec4** [comment]
I close this issue again, because a change of the GitHub theme fix it.
