### ISSUE TITLE
Remove encryption elements that are not used

### ISSUE THREAD

**Issue by dericed** [ietf-wg-cellar/matroska-specification#45]
Except for the ones used for DRM already [in use in WebM](https://www.webmproject.org/docs/webm-encryption/).

**Comment by dericed** [comment]
Moving @robUx4's issue from https://github.com/Matroska-Org/ebml-specification/issues/85 to the right repo.

**Comment by robUx4** [comment]
That would be 
* signature ones: `ContentEncoding\ContentEncryption\ContentSignature`, `ContentEncoding\ContentEncryption\ContentSigKeyID`, `ContentEncoding\ContentEncryption\ContentSigAlgo`, `ContentEncoding\ContentEncryption\ContentSigHashAlgo`.
* compression ones, `ContentEncoding\ContentEncoding\ContentCompression`, `ContentEncoding\ContentCompression\ContentCompAlgo`, `ContentEncoding\ContentCompression\ContentCompSettings`

The compression ones are definitely used in Matroska, even more formats are proposed (#423).

The signatures are unlikely to be used. We can either marked them as unusable (maxver=0) or deprecated (maxver=4).
