### ISSUE TITLE
Remove mentions of Control Track in the main spec

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#456]
So far there is no player (not even VLC with DVD menus) that can handle Control tracks. There is also no tool to create them.

This can be added in a separate document with its own RFC. We just need to keep the value in the `TrackEntry\TrackType` as reserved.

We can probably do the same with `complex` (mixed DV), `logo` (unused AFAIK). Not sure about `metadata`.

**Comment by hubblec4** [comment]
It is hard to find info about "Control Track".
What is this exactly, what does this track, how is the structure of such a track and how it/should it works?

**Comment by robUx4** [comment]
As the name suggests it's a track to control "things". Being a track you can put controls in the file with timestamps for commands to happen at a certain time during playback. This is a bit similar to what ChapterCodecs can do but without relying on chapters.

Just as a track it has "codecs" (and just has chapter codecs) which do various things and code they way to do actions in the player. Each player can support one of more "Control Codec". It's up to each codec to define what part of the playback experience they can control (just like chapter codecs).

The advantage over chapter codecs is that if you edit/cut the file the timestamp of such tracks is edited/cut the same way as any other track.

Given there is 0 "control codec" existing right now (while there are 2 chapter codecs), we don't need to support this feature for now.

**Comment by hubblec4** [comment]
Good to know that a ChapterCodec can do (almost) the same like a Control Track.

Then bye bye  > Control Track

On Doom9 you and Mosu had some posts about implementing Control Tracks posted. And some of this sounds it will be working in future.
