### ISSUE TITLE
Leave elements added in v5 out of the Matroska RFC

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#463]
So that #318 can be merged but without being mentioned in the RFC which is supposed to describe parts of Matroska already in use.

**Comment by robUx4** [comment]
#423 and #425 would benefit from this as well.

**Comment by robUx4** [comment]
We may need a different label to differentiate new v5 elements from new enum values as in #423.

**Comment by robUx4** [comment]
(there is one)

**Comment by hubblec4** [comment]
the new label "build+system" is not readable, I don't want open a new issue.

**Comment by robUx4** [comment]
It's [new label](https://github.com/ietf-wg-cellar/matroska-specification/issues?q=label%3A%22build+system%22+is%3Aclosed).

What are you viewing conditions that make it hard to read ? I don't have an exceptional view and yet I can see the labels just fine. Are you sure your screen contrast is not messed up ? It seems you only have an issue with light text on dark background which is what most people use in dark mode nowadays. 

There aren't a ton of available colors that are easily distinguishable from each other for labels. I'd rather be able to use all of them if we can solve this issue.

**Comment by robUx4** [comment]
reopened #445 not to pollute this discussion
