### ISSUE TITLE
Move Chapter codec definitions in separate documents

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#467]
Unlike chapters which are a core feature, each "codec" has its own definition that doesn't need to be set in the main document.

Just like we have a separate document for audio+video+subtitle codecs, we should have one for chapters (and even one per codec IMO).

These sections should move out of chapters.md:
```
### Matroska Script (0)
### DVD menu (1)
```

**Comment by hubblec4** [comment]
Yes I agree with this.
The Chapter codec should have its own document, because it is a own "world".
Many features are in my mind and waiting :-)
