### ISSUE TITLE
fix ChapterTimeEnd section

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#478]
It's currently giving examples on how some chapters end up with a duration of 0, but we have now established it's illegal:
`The value **MUST** be strictly greater than the ChapterTimeStart of the same ChapterAtom`

**Comment by hubblec4** [comment]
Can you provide such a sample mkv, and explain how this chapter is used?

**Comment by robUx4** [comment]
You mean writing an mkv file with 0 duration when we said we shouldn't do it ?

**Comment by robUx4** [comment]
Looking at my old DVDMenuxtractor output there are cases where only the lower nested `ChapterAtom` had a `ChapterTimeEnd` (it's legal since the element is not mandatory). The parent `ChapterAtom`'s assumed the end from the children end.

**Comment by hubblec4** [comment]
> You mean writing an mkv file with 0 duration when we said we shouldn't do it ?

No. You write:
> It's currently giving examples on how some chapters end up with a duration of 0, ....

So I guess you have an existing sample.

**Comment by hubblec4** [comment]
> Looking at my old DVDMenuxtractor output there are cases where only the lower nested ChapterAtom had a ChapterTimeEnd (it's legal since the element is not mandatory). The parent ChapterAtom's assumed the end from the children end.

Yeah that's the point why I asked in the past for the logic of the nested chapters which are ordered.

**Comment by robUx4** [comment]
In the Chapters > ChapterAtom > ChapterTimeEnd section of the document.
It states `If the duration of a Chapter is 0, this Chapter MUST be ignored.` and even has an example in the table.

Chapter 3 | 6000000000 | 6000000000 | 0 (chapter not used)

It should say illegal instead of not used.

**Comment by SpencerDawkins** [comment]
@robUx4 - if I might offer a suggestion, we usually say "illegal" in an RFC when something breaks an actual law, so someone comes to arrest you. 

Would "invalid" be more accurate?

**Comment by robUx4** [comment]
I did change the word illegal to invalid in the PR https://github.com/ietf-wg-cellar/matroska-specification/pull/504/files ;)

**Comment by SpencerDawkins** [comment]
@robUx4 - thank you! I figure if Matroska implementations actually do something ***illegal***, they'd probably arrest @mcr and me as the chairs ...
