### ISSUE TITLE
Add an EBML constraint about 0-length elements

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#500]
Although EBML allows an element with a default value to be written with just the ID and a length of 0, historically this is not properly supported by EBML parsers.
Recently we have started making element with a default value mandatory or not have a default value at all, to avoid this issue (ie making rules that will make legit Matroska files unreadable by current code) we should state that the 0-length feature is not supported in Matroska. The savings are minimal compared to a mandatory element not written.

This should be done after #495 which cleans the EBML sections at the beggining.

**Comment by hubblec4** [comment]
I like the 0-length feature and it should be used in Matroska.
In my own EBML project I have implemented this feature.

**Comment by robUx4** [comment]
We already established that libebml (mkvtoolnix and vlc) won't handle them properly, at least for default values that are not 0. If you use a 0 length with elements that don't have a 0 default value, the playback will be bogus.

It's easier to forbid this feature than forbid non-zero default values (which is already in use anyway so it can't happen). Or even adding a special case for when it is used. In the end the saving is too small to define a complicated rule when it should/should not be used.

Neither libebml nor libavformat write such files. So it's very likely that a lot of reader are not even handling this case properly.
libwebm seems to allow it for empty strings, but it seems more like an unintended feature.

The one case where all these libraries use a 0-length is when writing an `EbmlVoid`. That's something we do want to keep.
So the 0-length constraints should be on matroska elements, not EBML elements. Or on all elements except for `EbmlVoid`.

**Comment by hubblec4** [comment]
> We already established that libebml (mkvtoolnix and vlc) won't handle them properly, at least for default values that are not 0. If you use a 0 length with elements that don't have a 0 default value, the playback will be bogus.

Yeah I can understand this. MKVToolNix and VLC was start coded for long time.
I can now start from scratch with all the new info and for me is the 0-length feature very simple to implement.
And there is no issue if an element have not 0 as default.

But I think my voice is irrelevant and the 0-length feature will be forbidden.

**Comment by robUx4** [comment]
[libmkv](https://hg.mozilla.org/mozilla-central/file/FIREFOX_NIGHTLY_89_END/media/libmkv), formerly used in libvpx and still in the Firefox source tree, allows [writing any element with a zero length](https://hg.mozilla.org/mozilla-central/file/FIREFOX_NIGHTLY_89_END/media/libmkv/EbmlWriter.c#l22), more precisely strings, binary data and void elements.

**Comment by hubblec4** [comment]
Cool, is this a good chance to allow writing zero-length elements in EBML and Matroska?

**Comment by robUx4** [comment]
For `EBMLVoid` we definitely want it. The problem is only on integers/strings/floats (ie anything but binary blobs).
