### ISSUE TITLE
Add the bogus TagDefault value in the RFC

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#508]
`TagDefault` has an EBML ID `0x4484`, but some files exist with a value of `0x44B4`, referred as `MATROSKA_ID_TAGDEFAULT_BUG` in libavcodec.

We should probably mention this value in the specs. Probably in the section of deprecated elements that is introduced by #487.

**Comment by hubblec4** [comment]
Means that a parser have to check/used both IDs for this elemnt?

**Comment by robUx4** [comment]
As investigated by Paul Foley, the bogus value was introduced in libmatroska 0.7.3 and fixed/replaced in libmatroska 0.9.0.
The history of commits in the library doesn't go that far on [GitHub](https://github.com/Matroska-Org/libmatroska).

**Comment by robUx4** [comment]
> Means that a parser have to check/used both IDs for this element?

Not mandatory. libmatroska doesn't do it.
