### ISSUE TITLE
tags: COUNTRY description references wrong standard

### ISSUE THREAD

**Issue by mbunkus** [ietf-wg-cellar/matroska-specification#519]
Pointed out on IRC: the [description of the `COUNTRY` tag](https://github.com/ietf-wg-cellar/matroska-specification/blob/master/matroska_tags.xml#L34) references ISO 639-2 which is about language codes, not country codes.

Not sure what the correct reference would be. Back in the day the Matroska language form used two-letter top-level country-code domain names. So that's what was probably intended initially. However, [ISO 3166](https://en.wikipedia.org/wiki/Country_code_top-level_domain) is probably the better choice today (it's basically the same list, but the ccTLDs contain a couple of codes that aren't part of ISO 3166-1).

**Comment by JeromeMartinez** [comment]
As we are moving to IETF, maybe better to try to reuse IETF stuff about regions as it is in BCP 47 (I didn't find a specific RFC about countries/regions)
https://tools.ietf.org/search/bcp47#section-2.2.4
(in short: ISO 3166-1 and UN_M.49)

If we want to go in more details, we could use ISO 3166-1, ISO 3166-2 and UN_M.49. It would permit to get a mapping between old "advice" (ccTLDs) and the spec, e.g. ["NC" ccTLD](https://en.wikipedia.org/wiki/.nc) could be mapped to ["FR-NC"](https://en.wikipedia.org/wiki/ISO_3166-2:NC).

**Comment by SpencerDawkins** [comment]
I followed up with our ADs about this, because it's not my area of expertise, and they will be the ones who are trying to figure out if we're doing the right thing during AD Evaluation. 

I cc:ed the CELLAR mailing list, so you'll see any replies there as well. The link in the archives is https://mailarchive.ietf.org/arch/msg/cellar/MQr55hnPKiWPvzyaFyPFUXFPaMA/. 

(tagging @fpalombini and @mskucherawy, for ease of reference)

**Comment by robUx4** [comment]
Note that `ChapCountry` (@ablwr's favorite) is defined as such

> The countries corresponding to the string, same 2 octets country-codes as in Internet domains [@!IANADomains] based on [@!ISO3166-1] alpha-2 codes.
This Element **MUST** be ignored if the ChapLanguageIETF Element is used within the same ChapterDisplay Element.

**Comment by robUx4** [comment]
We also have that that use ISO 3166-1: `RECORDING_LOCATION`, `COMPOSITION_LOCATION` and `COMPOSER_NATIONALITY`.
They are all defined by

> same 2 octets country-codes as in Internet domains [@!IANADomains] based on [@!ISO3166-1] alpha-2 codes.

ie the same as `ChapCountry`
