### ISSUE TITLE
Don't rely on GPL only code

### ISSUE THREAD

**Issue by JeromeMartinez** [ietf-wg-cellar/matroska-specification#538]
IMO the IETF standard should rely on source code already available in a permisive license, in order, in order to let as much as people able to have a fully compliant support without having licensing issue if they don't want to reinvent the wheel or spend much time on creating a specific library.

Looks like LZO compression has this issue, the corresponding value could be set to "reserved for LZO, not part of this specification".

What do you think?

**Comment by mcr** [comment]
If the compression technique is described in a public document (that we can reference), and implementation of it is not covered by a software patent (or other equivalent IPR), then it doesn't matter what the copyright license on a single implementation is.
Someone could implement an MIT, Apache, or proprietary version of it for their code.
If LZO compression is useful, then reserve a code point for it.   If the GPL'ed library to decode it is a problem for some product, then that's an implementation issue.

I should point out that this is very different than H.264, which does have a patent on it, and can't be implemented without a license.

**Comment by robUx4** [comment]
Actually I just checked FFmpeg and there is an internal decoder under LGPL (which is a lot more friendly to use in commercial code).

The LZO format was reversed engineered but I couldn't find a permissive (MIT, BSD, public domain, etc) piece of code so far.

> If the compression technique is described in a public document

The [link I found](http://www.oberhumer.com/opensource/lzo/) doesn't have any spec. The source code is the documentation I guess... Implementations in other languages are also GPL, usually porting the C code to the other language.

This is different than H.264 which is an optional codec in Matroska. The compression method needs to be handled to read the content, even if you support the codec for the track. This is more "built-in" in Matroska.

The LGPL code is good news, but still not sufficient IMO. It's unlikely that it can be relicensed to something more permissive as it has about 10 different contributors over 10 years. So I still lean on discouraging people to use LZO in Matroska (which they probably did).

**Comment by robUx4** [comment]
side note: VLC only handles zlib and header compression in Matroska. So bzip and lzo can't be read there at least.

**Comment by robUx4** [comment]
I found an MIT version in C#, it used to use the (LGPL) FFmpeg code but was rewritten based on some [documentation in the Linux Kernel](https://www.kernel.org/doc/Documentation/lzo.txt), which has native support for LZO.

Maybe that's the spec link we should be using instead for the LZO specification.

**Comment by mcr** [comment]
> The [link I found](http://www.oberhumer.com/opensource/lzo/) doesn't have any spec. The source code is the documentation I guess... Implementations in other languages are also GPL, usually porting the C code to the other language.

If the spec is only in the form of GPL code, then that's not a sufficient spec for GPL-averse implementations/implementers to use.
The kernel.org specification would seem to be acceptable, but I suggest some wider review.
