### ISSUE TITLE
Update Tagging Identifiers documentation

### ISSUE THREAD

**Issue by manuelrn** [ietf-wg-cellar/matroska-specification#570]
Hello,

The [Tagging Identifiers documentation](https://www.matroska.org/technical/tagging.html) specifies the following:

- **TMDB** | UTF-8 | The Movie DB “movie_id” or “tv_id” identifier for movies/TV shows [@!MovieDB]. The variable length digits string MUST be prefixed with either “movie/” or “tv/”.
- **TVDB** | UTF-8 | The TV Database “Series ID” or “Episode ID” identifier for TV shows [@!TheTVDB]. Variable length all-digits string identifying a TV Show.
<br /><br />

In TMDB it is necessary to specify whether the content is series or movie because TMDB contains both content. And there are contents of both types that share the same identifier, so it is necessary to specify what type of content it is.

In TVDB it was not necessary to specify since it only contained series, but a while ago that changed. Now movies are also supported, so now it behaves exactly the same as TMDB does, now it is necessary to specify what type of content it is (because there are contents of both types that share the same identifier).
<br /><br />

In TMDB the content type is specified like this:
- movie/XXXXX
- tv/XXXXX

But in TVDB, what would it be like?
Same as TMDB ("movie/" and "tv/")? Or "movies/" and "series/"?

I think the second option is more appropriate. I comment this because the TMDB API is used with [/movie/{movie_id}](https://developers.themoviedb.org/3/movies/get-movie-details) and [/tv/{tv_id}](https://developers.themoviedb.org/3/tv/get-tv-details), but the TVDB API is used with [/movies/{id}](https://thetvdb.github.io/v4-api/#/Movies/getMovieBase) and [/series/{id}](https://thetvdb.github.io/v4-api/#/Series/getSeriesBase).
<br /><br />

Thanks and regards!

**Comment by robUx4** [comment]
We have to keep backward compatibility. So `TVDB` with just an ID must be considered as a TV show. We should add `movie/ID` to the same tag, but tools parsing `TVDB` will not understand this value and, worse, interpret it incorrectly as an ID.

So to preserve a safe backward compatibility, there should be a new tag name like `TVDB2` that would work like `TMBD`. The `TVDB` being the legacy version.

**Comment by manuelrn** [comment]
Agree @robUx4, that's perfect.

So, as I understand it, it would be like this:

For movies:
- `IMDB` : `ID`
- `TMDB` : `movie/ID`
- `TVDB2` : `movies/ID`

For series:
- `IMDB` : `ID`
- `TMDB` : `tv/ID`
- `TVDB` : `ID`
- `TVDB2` : `series/ID`
<br />

Could you confirm if this is correct?

Thanks again!

**Comment by robUx4** [comment]
That's correct. `TVDB` is only for series, `TVDB2` can be used for both and needs a prefix (that looks like the API).

**Comment by manuelrn** [comment]
Okay, thanks again @robUx4!
