### ISSUE TITLE
Add audio emphasis information per track

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#582]
Vinyl records are recorded with an [emphasis filter](https://en.wikipedia.org/wiki/RIAA_equalization) to avoid some avoid having too much bass. Most commly the RIAA phono curve is applied and un-applied in phono pre-amplifiers.

CDs also have an [emphasis bit](https://www.studio-nibble.com/cd/index.php?title=Pre-emphasis_(release_list)) that tells a filter has been applied.

If one records/rips raw data from the medium, the proprer filter has to be applied during playback. So there should be an element in the audio track entry of such Matroska files. This can't be a tag which should have no impact on playback.

There doesn't seem to be such information in Broadcast Wave File. So I'm not sure there's an existing standard for the values that are commonly found. We may need to define these values ourselves. With at least the RIAA curve and the CD one. For old phono records each company had its own curve, so there might be a lot of possible values. And we need a reliable source about the curve to use, for each value we define.

**Comment by retokromer** [comment]
>So I'm not sure there's an existing standard for the values that are commonly found.

From the top of my head, I don’t remember, but I will check that.

>We may need to define these values ourselves. With at least the RIAA curve and the CD one. For old phono records each company had its own curve, so there might be a lot of possible values. And we need a reliable source about the curve to use, for each value we define.

I fully agree and second this.

**Comment by robUx4** [comment]
FFmpeg has a few [hardcoded ones](https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/af_aemphasis.c#L56).

* CD Audio
* phono RIAA
* phono Columbia
* phono EMI
* phono BSI (78 rpm)
* FM 50µs (EU)
* FM 75µs (USoA)

They don't come with a well known define though. There should be something similar to the enum of transfer characteristics of video that we use, correspond to table 3 of ISO/IEC 23091-4 or ITU-T H.273.

**Comment by robUx4** [comment]
In the [MPEG Audio header](http://www.mpgedit.org/mpgedit/mpeg_format/mpeghdr.htm) there are 2 bits for emphasis (not read by FFmpeg):

* `00` none
* `01` 50/15 ms which correspond to the values used for CD Audio in FFmpeg
* `10` reserved
* `11` CCIT J.17 (mostly used on satellite ?)

[DVD Audio](http://www.dvdforum.org/images/Guideline1394V10R0_20020911.pdf) also have an emphasis bit which seems to use the same emphasis as CDs.
  | Emphasis           00 - none 01 - 50/15 ms 10 - reserved 11 - CCIT J.17
-- | --

**Comment by robUx4** [comment]
DV Also has an [emphasis bit](https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/dvenc.c#L130) and also tells which flavor to use (although this bit is reserved).
[SMPTE 314M](http://tvbook.narod.ru/itu/314m.pdf) seems to correspond as well, it's still the same 50/15 μs used in CD Audio.

There's an emphasis bit in [RTP](https://datatracker.ietf.org/doc/html/rfc3190#section-5) which is also the CD one.

**Comment by robUx4** [comment]
Marking this a Matroska v5 as it's a new element and shouldn't block the current Matroska publication.

**Comment by t-rapp** [comment]
> There doesn't seem to be such information in Broadcast Wave File. So I'm not sure there's an existing standard for the values that are commonly found.

The coding history lines (EBU Tech 3285 - Supp 2) provide some free text area which allows to store such information in a loosely structured way. When possible we (NOA) perform de-emphasis already during ingest using a high-quality digital filter and save the time constants of the de-emphasis filter in the coding history for future reference. That way the archived file is directly usable by players that do not offer (de)emphasis filtering themselves.

For example the following coding history lines:
```
A=ANALOGUE, M=stereo, T=Replayer;DN:SL-1210MK2;SN:2658
A=PCM, F=96000, W=32, M=stereo, T=AD;DN:N7000c;SN:#1256A04C
A=PCM, F=96000, W=32, M=stereo, T=Deemphasis;N:RIAA+Neumann;T1:3180;T2:75;T3:318;T4:3.18
```
define the time constants t<sub>1</sub>=3180µs, t<sub>2</sub>=75µs, t<sub>3</sub>=318µs, and t<sub>4</sub>=3.18µs of a RIAA deemphasis filter with additional Neumann constant. They correspond to the complex transfer function 
```
       (1 + t₃s)(1 + t₄s)
H(s) = ------------------
       (1 + t₁s)(1 + t₂s)
```

Just wanted to provide some use-case on the issue topic. But using time constants for the numerator / denominator parts might be an idea to describe (de)emphasis filter parameters in a general way.

**Comment by robUx4** [comment]
I have seen such mentions, at least for the material used for the recording. Is the `T=Deemphasis` a [NOA specific](https://www.noa-archive.com/assets/Uploads/ARSC-Paper-on-Digital-Deemphasis-Peter-Kuhnle-NOA.pdf) thing ? A similar `T=emphasis` might just as well define the emphasis that is present in the source and might be deemphasis'ed.

For record vinyl applying a digitial de-emphasis may be enough since, as that paper says it's reversible digitally. But care has to be taken on how to do it, for example the RIAA filter in libavcodec applies an extra brick-wall filter to filter high frequencies. That's that much frequencies lost that can't be recovered.

There's still the question of digital data that already exist with a pre-emphasis bit set. It should be possible to describe them. For example if you transfer them to FLAC without any processing.

A mathematical formula seems to be the most capable format, but even then it would probably not cover all the 78 RPM record variations between publishers. IMO for well established ones we can just use an enum. This would correspond to the bit found in existing digital files. We should however have a proper description (with equations) so that everyone agree on how to implement them.

**Comment by robUx4** [comment]
Also from that NOA document, one of the interresting part for phono record is that the analog pre-amplifier that also apply the de-emphasis are not actually 100% accurate and may vary over time (this is analog amplifying). This is why I'm recording my vinyl without the RIAA curve applied (the only coloration left is from the cartridge which can be estimated by playing white noise).

Although it's not playable as such, it eliminates some distortion from the original recording. And it's still necessary to "tag" these files properly so they can be played back correctly (I'm [working on that](https://code.videolan.org/videolan/vlc/-/merge_requests/1561)) or can be differentiated before post-processing.

There's also the question for archivists whether the pre-emphasis version is considered the original and the de-emphasis is the version that can be presented to the public.

**Comment by t-rapp** [comment]
> Is the `T=Deemphasis` a NOA specific thing?

Basically yes. In BWF Coding History anything on a line after `T=` is free text, but NOA uses some sub-tagging for adding structured data that can be processed when required. Also I'm not sure which processing steps will show up as entries (lines) in other software.

> A similar `T=emphasis` might just as well define the emphasis that is present in the source and might be deemphasis'ed.

The emphasis step is done during recording but the Coding History part usually starts with (analog) playback, so it won't show up in most cases.
