### ISSUE TITLE
TargetTypeValue table mentions CONCERT twice

### ISSUE THREAD

**Issue by ktmf01** [ietf-wg-cellar/matroska-specification#592]
I'm not posting this on the mailing list because it is a typo that I think doesn't warrant much discussion

https://github.com/ietf-wg-cellar/matroska-specification/blob/59f9977c0e56d0742b24502fbb40a7bf2b64e562/ebml_matroska.xml#L1507

**Comment by retokromer** [comment]
Nice catch!
