### ISSUE TITLE
Attaching codec to Matroska?

### ISSUE THREAD

**Issue by ktmf01** [ietf-wg-cellar/matroska-specification#597]
https://github.com/ietf-wg-cellar/matroska-specification/blob/59f9977c0e56d0742b24502fbb40a7bf2b64e562/diagram.md?plain=1#L284-L285

The notion that a codec can be attached seems to be in contradiction of this

https://github.com/ietf-wg-cellar/matroska-specification/blob/59f9977c0e56d0742b24502fbb40a7bf2b64e562/attachments.md?plain=1#L12

Which of the two is true?

**Comment by robUx4** [comment]
Indeed, the security addition is newer and makes more sense. The same goes for programs.
