### ISSUE TITLE
MIME type -> media type?

### ISSUE THREAD

**Issue by ktmf01** [ietf-wg-cellar/matroska-specification#662]
I'm by no extend knowledgeable in this matter, but as far as I know 'MIME type' is an old name for what is now known as 'media type'. I don't know whether it might come up as problematic that the 'old' name is used quite a lot of times in the matroska specification?

**Comment by mcr** [comment]
Yes, MIME type is what we used to call it when it was used for email... and then HTTP took it over, and it became media-type.
We should change the name in the document.

**Comment by robUx4** [comment]
Thanks for the report!
