### ISSUE TITLE
SeekID Length attribute

### ISSUE THREAD

**Issue by hubblec4** [ietf-wg-cellar/matroska-specification#725]
The current value of the Length attribute is: "<=4", but the documention of the `SeekID` element say
"The binary EBML ID of a Top-Level Element."

A Top-Level element uses a class-D ID which is 4 bytes in length.

Should the value of the Length attribute changed to "4"?

**Comment by robUx4** [comment]
There is no notion of Class D in the spec anymore. And there is not a restriction on the size of Top Level Elements either.

There's only this text in the Matroska ID IANA registry that mentions how the size of ID's should be picked:

> Given the scarcity of the One-octet Element IDs, they should only be created to save space for elements found many times in a file.
For example within a BlockGroup or Chapters. The Four-octet Element IDs are mostly for synchronization of large elements.
They should only be used for such high level elements.

**Comment by hubblec4** [comment]
> Design Rules
The Root Element and all Top-Levels Elements use 4 octets for their EBML Element ID -- i.e. Segment and direct children of Segment.

I had read this in index_matroska.md.

**Comment by robUx4** [comment]
Indeed, although the text is not normative. It doesn't say MUST use 4 octets. However the rule has been like that forever. libmatroska has enforced that rule for a long time: https://github.com/Matroska-Org/libmatroska/blame/4a7222ce81a7c13d31bdac6b8f6ee6d266ca4db9/matroska/KaxSemantic.h#L52

Changing it now means custom files that, for some reason, uses 3-octets long elements will no longer be valid. Technically we're suppose to describe what Matroska up until now has been doing. But in this case, just as with plenty of elements we decided were unlikely to be used and got deprecated, we can probably safely change the rule here.

**Comment by JeromeMartinez** [comment]
> Technically we're suppose to describe what Matroska up until now has been doing. 

... in the real world and the most used, not the corner cases, so it is fine IMO.

> we can probably safely change the rule here.

+1.

**Comment by retokromer** [comment]
> we can probably safely change the rule here.

+1
