### ISSUE TITLE
EBML Lacing details are incorrect

### ISSUE THREAD

**Issue by austinleroy** [ietf-wg-cellar/matroska-specification#726]
Hello! I'm opening this issue to describe a problem in the specification documentation related to this section: 

https://github.com/ietf-wg-cellar/matroska-specification/blob/bdb0b3c01a13537ad6f60d90ba80cf89ff2360c2/notes.md#ebml-lacing

The documentation states:
> The first frame size is encoded as an EBML Unsigned Integer Element value. The other frame sizes are encoded as a difference with the previous frame size as EBML Signed Integer Element values. That corresponds to an EBML Data Size Values with two’s complement notation with the leftmost bit being the sign bit as found in [@!RFC8794], giving this range of values:

The part I'd like to point out in the above excerpt is that subsequent frame sizes should be encoded as EBML Signed Integer Element values, which use *two's complement notation*.

The document then follows with a table showing an example encoding for a block with frame sizes of 800, 500, and 1000.  The relevant part here is the size of the second frame:

> 7-8 | 0x5E 0xD3 | Size of the second frame (500 - 800 = -300 = - 0x12C + 0x1FFF + 0x4000)

The size expressed as a decimal is definitely "-300".  However, the binary output shown **is not -300 in two's complement notation**, and the formula in parenthesis **does not result in two's complement notation**.  The correct binary for -300 (in two's complement notation using 14 bits, which is the number of usable bits for the value of the vint) is {11 1110 1101 0100}.  Prepending the vint marker {01} for two value bytes gives us: 0x7ED4.

Is there a consensus on how ebml lacing should actually be represented?  If so, it'd be great to update the documentation to reflect that correctly.

Handy calculator for two's complement: https://www.omnicalculator.com/math/twos-complement

**Comment by austinleroy** [comment]
I did some more digging on this, and it looks like the existing code in the libmatroska repo for writing EBML Lacing sizes uses the "add/subtract half the range" approach: https://github.com/Matroska-Org/libebml/blob/efac02cd5a0d6b8d07b075b0bc0a62baf896d5ee/src/EbmlElement.cpp#L130

It looks like the above linked method is only used inside [KaxBlock.cpp](https://github.com/Matroska-Org/libmatroska/blob/4f1d7af84dd7a4baf81fdf3746c5184820d77c12/src/KaxBlock.cpp) (which deals with block lacings). It may also be worth mentioning that this method only handles 32-bit integers (whereas anything ebml related should support 64-bit).

I don't know whether or not the code should be treated as the source of truth for the specification, but I thought it'd be worth bringing this up.

**Comment by hubblec4** [comment]
Maybe I'm wrong, but all work's fine for me with the SingedVINT like it is.

Yes there are only one point at the moment were a SignedVINT for a Size is used. (Mostly sizes are positive Integers).
And the reason why this method is "limited" to 32-bit, because frames are small in size and a differennce of such frames are more smaller.
I guess it is almost impossible to get size-differences with more than 32-bit.

**Comment by austinleroy** [comment]
I'm not trying to say the code doesn't work as-is (i.e. able to store and then read a signed integer), I'm just pointing out that it doesn't use two's complement notation like the spec describes.

I agree that it's highly unlikely a frame size difference will ever exceed a 32-bit int, but again, I'm just highlighting that the code differs from the specification language which implies sizes up to 8 bytes.

All I'm really looking for is clarification on what ebml lacing sizes *should* look like. If the spec language needs to be updated to match what the library code is doing that's fine; if the code needs to change that's fine too (although that's a can of worms because it would invalidate every ebml-laced file previously written by the library). The problem isn't whether or not a specific method works, it's that the correct method isn't clearly defined.

**Comment by robUx4** [comment]
Hi,

Thanks for pointing this out. I think we should stick to the "encode as a signed EBML integer" approach. It's better described in the EBML RFC (hopefully) anyway. It doesn't have any 32-bit limitation. That may be an implementation bug/limitation of libmatroska.

**Comment by robUx4** [comment]
The [EBML RFC](https://www.rfc-editor.org/rfc/rfc8794#name-signed-integer-element) is more vague than the Matroska one in this case (no example). It does mention the two's complement though. 

libmatroska is using the libebml functions [CodedValueLengthSigned()](https://github.com/Matroska-Org/libebml/blob/a81936929f9c2c21e0ed0e11476df42a01111eb8/src/EbmlElement.cpp#L130) and [CodedSizeLengthSigned()](https://github.com/Matroska-Org/libebml/blob/a81936929f9c2c21e0ed0e11476df42a01111eb8/src/EbmlElement.cpp#L93). They are in fact not the same functions used to read/write an [EBMLSInteger](https://github.com/Matroska-Org/libebml/blob/a81936929f9c2c21e0ed0e11476df42a01111eb8/src/EbmlSInteger.cpp#L148). We may move these functions into libmatroska since they are only useful there (cc @mbunkus).

That's where the "EBML-like encoding" comes from in the spec. It looks the same but it may not be entirely the same. I'd have to run the code on various values to check if they actually give the same result or not.

As for the explanation, we might just describe how that libebml code works, which is to shift the value to the shortest positive value (+63, +8191, +1048575 and +134217727) and encode that as a unsigned EBML value. On reading the opposite shift is done depending the size of the element.

**Comment by robUx4** [comment]
I ran this small code in libebml and the results are definitely different between the 2 algorithms (and there seems to be a waste of octet with some values in EbmlSInteger (128 and 129))

```cpp
#include <ebml/EbmlElement.h>
#include <ebml/EbmlSInteger.h>
#include <ebml/MemIOCallback.h>

#include <iostream>
#include <iomanip>

using namespace libebml;

DECLARE_EBML_SINTEGER(EbmlInt)
  public:
        EBML_CONCRETE_CLASS(EbmlInt)
};

EbmlInt::EbmlInt()
{}
DEFINE_EBML_CLASS_GLOBAL(EbmlInt, 0xAA, 1, "EbmlSInt test")

static void printValue(std::int64_t i, int coded_size, const binary *read)
{
    std::cout << std::dec << i << ':' << coded_size << " [";
    for (int j=0; j<coded_size; j++)
        std::cout << std::setw(2) << std::setfill('0') << std::hex << (int)read[j];
    std::cout << "]" << std::endl;
}

static void testValue(std::int64_t i)
{
    binary read[8];
    int coded_size = CodedSizeLengthSigned(i, 0);
    CodedValueLengthSigned(i, coded_size, read);
    printValue(i, coded_size, read);

    EbmlInt test;
    MemIOCallback memWriter;
    test.SetValue(i);
    test.UpdateSize(false, true);
    test.RenderData(memWriter, true);
    printValue(i, test.GetSize(), memWriter.GetDataBuffer());
}

int main(void)
{
    for (std::int64_t i = -129; i <= 129; i++)
    {
        testValue(i);
    }
    testValue(-254);
    testValue(-300);

    return 0;
}
```

```
-129:2 [5f7e]
-129:2 [ff7f]
-128:2 [5f7f]
-128:1 [80]
-127:2 [5f80]
-127:1 [81]
-126:2 [5f81]
-126:1 [82]
-125:2 [5f82]
-125:1 [83]
-124:2 [5f83]
-124:1 [84]
-123:2 [5f84]
-123:1 [85]
-122:2 [5f85]
-122:1 [86]
-121:2 [5f86]
-121:1 [87]
-120:2 [5f87]
-120:1 [88]
-119:2 [5f88]
-119:1 [89]
-118:2 [5f89]
-118:1 [8a]
-117:2 [5f8a]
-117:1 [8b]
-116:2 [5f8b]
-116:1 [8c]
-115:2 [5f8c]
-115:1 [8d]
-114:2 [5f8d]
-114:1 [8e]
-113:2 [5f8e]
-113:1 [8f]
-112:2 [5f8f]
-112:1 [90]
-111:2 [5f90]
-111:1 [91]
-110:2 [5f91]
-110:1 [92]
-109:2 [5f92]
-109:1 [93]
-108:2 [5f93]
-108:1 [94]
-107:2 [5f94]
-107:1 [95]
-106:2 [5f95]
-106:1 [96]
-105:2 [5f96]
-105:1 [97]
-104:2 [5f97]
-104:1 [98]
-103:2 [5f98]
-103:1 [99]
-102:2 [5f99]
-102:1 [9a]
-101:2 [5f9a]
-101:1 [9b]
-100:2 [5f9b]
-100:1 [9c]
-99:2 [5f9c]
-99:1 [9d]
-98:2 [5f9d]
-98:1 [9e]
-97:2 [5f9e]
-97:1 [9f]
-96:2 [5f9f]
-96:1 [a0]
-95:2 [5fa0]
-95:1 [a1]
-94:2 [5fa1]
-94:1 [a2]
-93:2 [5fa2]
-93:1 [a3]
-92:2 [5fa3]
-92:1 [a4]
-91:2 [5fa4]
-91:1 [a5]
-90:2 [5fa5]
-90:1 [a6]
-89:2 [5fa6]
-89:1 [a7]
-88:2 [5fa7]
-88:1 [a8]
-87:2 [5fa8]
-87:1 [a9]
-86:2 [5fa9]
-86:1 [aa]
-85:2 [5faa]
-85:1 [ab]
-84:2 [5fab]
-84:1 [ac]
-83:2 [5fac]
-83:1 [ad]
-82:2 [5fad]
-82:1 [ae]
-81:2 [5fae]
-81:1 [af]
-80:2 [5faf]
-80:1 [b0]
-79:2 [5fb0]
-79:1 [b1]
-78:2 [5fb1]
-78:1 [b2]
-77:2 [5fb2]
-77:1 [b3]
-76:2 [5fb3]
-76:1 [b4]
-75:2 [5fb4]
-75:1 [b5]
-74:2 [5fb5]
-74:1 [b6]
-73:2 [5fb6]
-73:1 [b7]
-72:2 [5fb7]
-72:1 [b8]
-71:2 [5fb8]
-71:1 [b9]
-70:2 [5fb9]
-70:1 [ba]
-69:2 [5fba]
-69:1 [bb]
-68:2 [5fbb]
-68:1 [bc]
-67:2 [5fbc]
-67:1 [bd]
-66:2 [5fbd]
-66:1 [be]
-65:2 [5fbe]
-65:1 [bf]
-64:2 [5fbf]
-64:1 [c0]
-63:1 [80]
-63:1 [c1]
-62:1 [81]
-62:1 [c2]
-61:1 [82]
-61:1 [c3]
-60:1 [83]
-60:1 [c4]
-59:1 [84]
-59:1 [c5]
-58:1 [85]
-58:1 [c6]
-57:1 [86]
-57:1 [c7]
-56:1 [87]
-56:1 [c8]
-55:1 [88]
-55:1 [c9]
-54:1 [89]
-54:1 [ca]
-53:1 [8a]
-53:1 [cb]
-52:1 [8b]
-52:1 [cc]
-51:1 [8c]
-51:1 [cd]
-50:1 [8d]
-50:1 [ce]
-49:1 [8e]
-49:1 [cf]
-48:1 [8f]
-48:1 [d0]
-47:1 [90]
-47:1 [d1]
-46:1 [91]
-46:1 [d2]
-45:1 [92]
-45:1 [d3]
-44:1 [93]
-44:1 [d4]
-43:1 [94]
-43:1 [d5]
-42:1 [95]
-42:1 [d6]
-41:1 [96]
-41:1 [d7]
-40:1 [97]
-40:1 [d8]
-39:1 [98]
-39:1 [d9]
-38:1 [99]
-38:1 [da]
-37:1 [9a]
-37:1 [db]
-36:1 [9b]
-36:1 [dc]
-35:1 [9c]
-35:1 [dd]
-34:1 [9d]
-34:1 [de]
-33:1 [9e]
-33:1 [df]
-32:1 [9f]
-32:1 [e0]
-31:1 [a0]
-31:1 [e1]
-30:1 [a1]
-30:1 [e2]
-29:1 [a2]
-29:1 [e3]
-28:1 [a3]
-28:1 [e4]
-27:1 [a4]
-27:1 [e5]
-26:1 [a5]
-26:1 [e6]
-25:1 [a6]
-25:1 [e7]
-24:1 [a7]
-24:1 [e8]
-23:1 [a8]
-23:1 [e9]
-22:1 [a9]
-22:1 [ea]
-21:1 [aa]
-21:1 [eb]
-20:1 [ab]
-20:1 [ec]
-19:1 [ac]
-19:1 [ed]
-18:1 [ad]
-18:1 [ee]
-17:1 [ae]
-17:1 [ef]
-16:1 [af]
-16:1 [f0]
-15:1 [b0]
-15:1 [f1]
-14:1 [b1]
-14:1 [f2]
-13:1 [b2]
-13:1 [f3]
-12:1 [b3]
-12:1 [f4]
-11:1 [b4]
-11:1 [f5]
-10:1 [b5]
-10:1 [f6]
-9:1 [b6]
-9:1 [f7]
-8:1 [b7]
-8:1 [f8]
-7:1 [b8]
-7:1 [f9]
-6:1 [b9]
-6:1 [fa]
-5:1 [ba]
-5:1 [fb]
-4:1 [bb]
-4:1 [fc]
-3:1 [bc]
-3:1 [fd]
-2:1 [bd]
-2:1 [fe]
-1:1 [be]
-1:1 [ff]
0:1 [bf]
0:1 [00]
1:1 [c0]
1:1 [01]
2:1 [c1]
2:1 [02]
3:1 [c2]
3:1 [03]
4:1 [c3]
4:1 [04]
5:1 [c4]
5:1 [05]
6:1 [c5]
6:1 [06]
7:1 [c6]
7:1 [07]
8:1 [c7]
8:1 [08]
9:1 [c8]
9:1 [09]
10:1 [c9]
10:1 [0a]
11:1 [ca]
11:1 [0b]
12:1 [cb]
12:1 [0c]
13:1 [cc]
13:1 [0d]
14:1 [cd]
14:1 [0e]
15:1 [ce]
15:1 [0f]
16:1 [cf]
16:1 [10]
17:1 [d0]
17:1 [11]
18:1 [d1]
18:1 [12]
19:1 [d2]
19:1 [13]
20:1 [d3]
20:1 [14]
21:1 [d4]
21:1 [15]
22:1 [d5]
22:1 [16]
23:1 [d6]
23:1 [17]
24:1 [d7]
24:1 [18]
25:1 [d8]
25:1 [19]
26:1 [d9]
26:1 [1a]
27:1 [da]
27:1 [1b]
28:1 [db]
28:1 [1c]
29:1 [dc]
29:1 [1d]
30:1 [dd]
30:1 [1e]
31:1 [de]
31:1 [1f]
32:1 [df]
32:1 [20]
33:1 [e0]
33:1 [21]
34:1 [e1]
34:1 [22]
35:1 [e2]
35:1 [23]
36:1 [e3]
36:1 [24]
37:1 [e4]
37:1 [25]
38:1 [e5]
38:1 [26]
39:1 [e6]
39:1 [27]
40:1 [e7]
40:1 [28]
41:1 [e8]
41:1 [29]
42:1 [e9]
42:1 [2a]
43:1 [ea]
43:1 [2b]
44:1 [eb]
44:1 [2c]
45:1 [ec]
45:1 [2d]
46:1 [ed]
46:1 [2e]
47:1 [ee]
47:1 [2f]
48:1 [ef]
48:1 [30]
49:1 [f0]
49:1 [31]
50:1 [f1]
50:1 [32]
51:1 [f2]
51:1 [33]
52:1 [f3]
52:1 [34]
53:1 [f4]
53:1 [35]
54:1 [f5]
54:1 [36]
55:1 [f6]
55:1 [37]
56:1 [f7]
56:1 [38]
57:1 [f8]
57:1 [39]
58:1 [f9]
58:1 [3a]
59:1 [fa]
59:1 [3b]
60:1 [fb]
60:1 [3c]
61:1 [fc]
61:1 [3d]
62:1 [fd]
62:1 [3e]
63:1 [fe]
63:1 [3f]
64:2 [603f]
64:1 [40]
65:2 [6040]
65:1 [41]
66:2 [6041]
66:1 [42]
67:2 [6042]
67:1 [43]
68:2 [6043]
68:1 [44]
69:2 [6044]
69:1 [45]
70:2 [6045]
70:1 [46]
71:2 [6046]
71:1 [47]
72:2 [6047]
72:1 [48]
73:2 [6048]
73:1 [49]
74:2 [6049]
74:1 [4a]
75:2 [604a]
75:1 [4b]
76:2 [604b]
76:1 [4c]
77:2 [604c]
77:1 [4d]
78:2 [604d]
78:1 [4e]
79:2 [604e]
79:1 [4f]
80:2 [604f]
80:1 [50]
81:2 [6050]
81:1 [51]
82:2 [6051]
82:1 [52]
83:2 [6052]
83:1 [53]
84:2 [6053]
84:1 [54]
85:2 [6054]
85:1 [55]
86:2 [6055]
86:1 [56]
87:2 [6056]
87:1 [57]
88:2 [6057]
88:1 [58]
89:2 [6058]
89:1 [59]
90:2 [6059]
90:1 [5a]
91:2 [605a]
91:1 [5b]
92:2 [605b]
92:1 [5c]
93:2 [605c]
93:1 [5d]
94:2 [605d]
94:1 [5e]
95:2 [605e]
95:1 [5f]
96:2 [605f]
96:1 [60]
97:2 [6060]
97:1 [61]
98:2 [6061]
98:1 [62]
99:2 [6062]
99:1 [63]
100:2 [6063]
100:1 [64]
101:2 [6064]
101:1 [65]
102:2 [6065]
102:1 [66]
103:2 [6066]
103:1 [67]
104:2 [6067]
104:1 [68]
105:2 [6068]
105:1 [69]
106:2 [6069]
106:1 [6a]
107:2 [606a]
107:1 [6b]
108:2 [606b]
108:1 [6c]
109:2 [606c]
109:1 [6d]
110:2 [606d]
110:1 [6e]
111:2 [606e]
111:1 [6f]
112:2 [606f]
112:1 [70]
113:2 [6070]
113:1 [71]
114:2 [6071]
114:1 [72]
115:2 [6072]
115:1 [73]
116:2 [6073]
116:1 [74]
117:2 [6074]
117:1 [75]
118:2 [6075]
118:1 [76]
119:2 [6076]
119:1 [77]
120:2 [6077]
120:1 [78]
121:2 [6078]
121:1 [79]
122:2 [6079]
122:1 [7a]
123:2 [607a]
123:1 [7b]
124:2 [607b]
124:1 [7c]
125:2 [607c]
125:1 [7d]
126:2 [607d]
126:1 [7e]
127:2 [607e]
127:1 [7f]
128:2 [607f]
128:2 [0080]
129:2 [6080]
129:2 [0081]
-254:2 [5f01]
-254:2 [ff02]
-300:2 [5ed3]
-300:2 [fed4]
```

So the definitions should not be the same. I think the explanation in the table is correct, but we need to put it into words.

**Comment by ktmf01** [comment]
Looking at the table it seems my observation wasn't entirely correct. It seems the size of the first frame is also encoded with a signed value. That simplifies the wording I guess. Another try

> The EBML lacing encodes the frame size with a VINT encoding as used in EBML [@!RFC8794], modified to store signed numbers. The bits 5-6 of the Block Header flags are set to 11.
>
> The Block data with laced frames is stored as follows:
>
>    Lacing Head on 1 Octet: Number of frames in the lace minus 1.
    Lacing size of each frame except the last one.
    Binary data of each frame consecutively.
>
> Each frame size is stored in a VINT, with a mapping from signed to unsigned numbers. Decoding the unsigned number stored in a VINT to a signed number is done by subtracting 2 ** (7*n-1)-1, where 'n' is the octet size of the VINT.

**Comment by hubblec4** [comment]
>  It seems the size of the first frame is also encoded with a signed value.

I'm very sure the first frames size is encoded as unsigned value.

**Comment by hubblec4** [comment]
I had also waste a lot of time when I was coding the lacing size algo.

I also thought first the SignedInteger type is used, but the values don't match with the values from files created with MKVToolNix.

The big problem is that EBML defines only the VINT type, which is equal to the Unsigned VINT.

But the Signed VINT is not defined.

After a look at this [CodedValueLengthSigned](https://github.com/Matroska-Org/libebml/blob/a81936929f9c2c21e0ed0e11476df42a01111eb8/src/EbmlElement.cpp#L130) function 
and this ReadCodedSizeSignedValue function it was clear whats going on.
A sigend VINT is used.

**Comment by robUx4** [comment]
For the record, here is how it's done in libavformat: https://github.com/FFmpeg/FFmpeg/blob/3153c441e1d980ff9931ed26a0e01b4e366ac521/libavformat/matroskadec.c#L3249

```c
        n = ebml_read_num(matroska, pb, 8, &num, 1);
        if (n < 0)
            return n;
        if (num > INT_MAX)
            return AVERROR_INVALIDDATA;

        total = lace_size[0] = num;
        offset = n;
        for (n = 1; n < *laces - 1; n++) {
            int64_t snum;
            int r;
            r = matroska_ebmlnum_sint(matroska, pb, &snum);
            if (r < 0)
                return r;
            if (lace_size[n - 1] + snum > (uint64_t)INT_MAX)
                return AVERROR_INVALIDDATA;

            lace_size[n] = lace_size[n - 1] + snum;
            total       += lace_size[n];
            offset      += r;
        }
```

**Comment by ktmf01** [comment]
As I feel the point didn't fully come across on the Cellar meeting, I would like to explain why I think 'signed VINT' isn't less efficient then EBML Signed integer.

The code posted above showed that 'signed VINT' uses 1 byte for values between -63 and 63 and 2 byte for values slightly beyond those boundaries. EBML Signed integer uses 1 byte for values between -128 and 127.

However, that fails to take into account that an EBML Signed integer would need an additional byte to describe its length, while 'signed VINT' does that by itself. So, in fact, the smallest an EBML Signed integer could be is 2 bytes, 1 byte to describe the length and 1 byte for the actual value.

This means the following.
'Signed VINT' uses
- 1 byte for values [-63,63]
- 2 bytes for values [-8191,8191]
- 3 bytes for values [-1048575,1048575]
- 4 bytes for values [-268435455,268435455]

EBML Signed integer would need
- 2 bytes for values [-128,127]
- 3 bytes for values [-32768,32767]
- 4 bytes for values [-8388608,8388607]

So, as I see it, it seems 'Signed VINT' is actually more efficient for most values, not less efficient.

**Comment by hubblec4** [comment]
Keep in mind there is a small issue for the upper boundaries.

A `Signed VINT` of one byte can store the value 64 als well. I hope I had understand @robUx4 correctly.

A value of 64 is coded as 0xFF. For an unsigned VINT would mean that the size is unknown, because all bits are set to 1.
But this is not the case for a `Signed VINT`.


- 1 byte for values [-63, 64]
- 2 bytes for values [-8191, 8192]
- 3 bytes for values [-1048575, 1048576]
- 4 bytes for values [-268435455, 268435456]

**Comment by austinleroy** [comment]
Pitching in about the libavformat code for anyone following along who isn't as technical:

The code here

> /* make signed (weird way) */
>    *num = unum - ((1LL << (7 * res - 1)) - 1);

is the approach described earlier as "subtract half the range" (meaning the current libavformat code is consistent with libmatroska/libebml).

---------------------------------------------------------------------------------

I like the updated description for EBML Lacing in #733 - it's explicit and consistent with how the code works.

**Comment by robUx4** [comment]
> A value of 64 is coded as 0xFF. For an unsigned VINT would mean that the size is unknown, because all bits are set to 1.

This is a valid remark. It could be intrepreted that way. But in RFC8794 the VINT description is separated from the actual usage which is is to express the size of the data folling the size part. That part contains only the size as @ktmf01 said earlier. There's no notion of unknown-size involved here which is, by the way, restricted to EBML Master elements. 

The updated table also clearly shows that 2<sup>6</sup>, 2<sup>13</sup>, 2<sup>20</sup>, etc are included. In case someone wonders if that value is OK or not.

However this limitation might be why these values where excluded when writing the values. I don't remember at all why it was that way. But some testing on existing code is needed.

**Comment by robUx4** [comment]
I updated my test code to verify the reading of the new expanded boundaries work properly with older versions of libmatroska and it works:

```cpp
static void testReading(const binary *buf, std::size_t bufsize, std::int64_t expected)
{
    std::uint32_t bufSize = bufsize;
    std::uint64_t sizeUnknown;
    std::uint64_t val = ReadCodedSizeSignedValue(buf, bufSize, sizeUnknown);
    std::cout << std::dec << "expected " << expected << " got " << val << std::endl;
}

int main(void)
{
    for (std::int64_t i = -129; i <= 129; i++)
    {
        testValue(i);
    }
    testValue(-254);
    testValue(-300);
    testValue(SignedVINT_MAX(1));
    testValue(SignedVINT_MAX(2));
    testValue(SignedVINT_MAX(3));
    testValue(SignedVINT_MAX(4));

    binary test1[1] = { 0xFF };
    testReading(test1, 1, SignedVINT_MAX(1));
    binary test2[2] = { 0x7F, 0xFF };
    testReading(test2, 2, SignedVINT_MAX(2));
    binary test3[3] = { 0x3F, 0xFF, 0xFF };
    testReading(test3, 3, SignedVINT_MAX(3));
    binary test4[4] = { 0x1F, 0xFF, 0xFF, 0xFF };
    testReading(test4, 4, SignedVINT_MAX(4));

    return 0;
}
```

Giving
```
64:2 [603f]
64:1 [ff]
64:1 [40]
8192:3 [301fff]
8192:2 [7fff]
8192:2 [2000]
1048576:4 [180fffff]
1048576:3 [3fffff]
1048576:3 [100000]
134217728:5 [0808000000]
134217728:4 [1fffffff]
134217728:4 [08000000]
expected 64 got 64
expected 8192 got 8192
expected 1048576 got 1048576
expected 134217728 got 134217728
```
