### ISSUE TITLE
String element range values

### ISSUE THREAD

**Issue by hubblec4** [ietf-wg-cellar/matroska-specification#737]
This is the same like [Binary element range values](https://github.com/ietf-wg-cellar/matroska-specification/issues/730).

Currently there are only one element: `TargetType` which uses the `range` attribute.

A String is not useable as enum, right?

**Comment by hubblec4** [comment]
> we should not define ranges for strings.

OK. but how should the restrictions be defined?

I think it is necessary to define restriction vaules for String-Type elements.

For example the old `Language` elements -> `ChapLanguage`
There is a description which string values can be used (ISO 639-3) and it would be to much content to define all the language codes as valid strings.

**Comment by robUx4** [comment]
We are not going to copy the whole ISO 639-3 codes in the spec. We do copy a few common ISO values (like the colorimetry fields) when it's a decent size (our document is already big enough like that). And language codes being strings, it's not very useful to generate code.

You can restrict values you can put in a string: with an enum or a with written text. But a range is not really possible here.

**Comment by hubblec4** [comment]
> We are not going to copy the whole ISO 639-3 codes in the spec.

Yes, that would be so crazy. :-)

> We do copy a few common ISO values (like the colorimetry fields)

Yes, and this are real enums, perfect for machine reading.


> You can restrict values you can put in a string: with an enum or a with written text.

OK, means that `restricted enums` can be used for String types although EBML excludes this types?

**Comment by robUx4** [comment]
> OK, means that restricted enums can be used for String types although EBML excludes this types?

There is nothing in [RFC8794](https://www.rfc-editor.org/rfc/rfc8794#name-enum-element) that restricts the type for enums. And we do use it in Matroska for the `TargetType` element.

**Comment by hubblec4** [comment]
OK. But I thought I had read that `enums` are only used for numerical element types.
