### ISSUE TITLE
TrackOverlay is unusable

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#741]
We have a TrackOverlay element that is supposed to be used with SilentTracks. Except SilentTracks are deprecated.

Either we bring back SilentTracks or we deprecate the TrackOverlay. Just like SilentTracks it's likely never used. The idea was that one could add bits of video/audio in a separate track to replace the content of the main track. That makes editing easier. But that means a player has to open each silent track and when it encounter content, it replaces the content of the main track.

IMO it should have been removed in #516. For the same reason that seeking doesn't take in account these tracks (although it could be a rule to use this). Maybe we can revive this properly in v5, as mentioned in that PR.

**Comment by hubblec4** [comment]
I hav e never seen a mkv with `TrackOverlay` element. Exists a real file which these element?

I think, make it deprecated is the easiest way.
