### ISSUE TITLE
review Haali's codec spec documentation

### ISSUE THREAD

**Issue by dericed** [ietf-wg-cellar/matroska-specification#78]
codec_specs.md says (or used to say):

> As an additional resource to this page Haali has created a [list of codec IDs in a PDF](http://haali.su/mkv/codecs.pdf).

This resource should be reviewed to determine what, if any, content should be incorporated into codec_specs.md.

**Comment by robUx4** [comment]
With #917 and #918 we have all the codecs mentioned there.
