### ISSUE TITLE
Clarification of ProjectionPoseRoll direction

### ISSUE THREAD

**Issue by ls-2037** [ietf-wg-cellar/matroska-specification#822]
It's unclear what is meant by the "forward vector" in the ProjectionPoseRoll element documentation (https://www.matroska.org/technical/elements.html#ProjectionPoseRoll). As a result, some players rotate clockwise and some rotate counter-clockwise.

It is stated unambiguously in the specification notes (https://www.matroska.org/technical/notes.html#rotation) that the correct video display rotation direction for a positive ProjectionPoseRoll value is counter-clockwise. I wanted to confirm that that was the case: ProjectionPoseRoll=90 should cause the video to be rotated 90 degrees counter-clockwise during playback.

See also https://github.com/mpv-player/mpv/issues/13830.

**Comment by robUx4** [comment]
Yes `ProjectionPoseRoll` without a pitch/yaw corresponds to a standard counter-clockwise rotation. The text comes from @dericed at bc02d123fa15dd04a9b97d892d2222eab9380b66. I assume forward means an axis going towards you as opposed to backward that would go further from you.

Not sure what a more mathematical unambiguous term could be.

**Comment by kasper93** [comment]
@nevcairiel @v0lt Do you agree to implement this change in your projects? I will handle the update for mpv, but I'd like to synchronize with you both to ensure we make these changes around the same time. This coordination will help prevent confusion among users.

**Comment by v0lt** [comment]
> Do you agree to implement this change in your projects?

I would like to see 2 MKV reference samples rotated by +90 and -90 degrees. A good sample would be a vertical video shot on a regular smartphone and converted to MKV.

**Comment by hubblec4** [comment]
> I would like to see 2 MKV reference samples rotated by +90 and -90 degrees.

https://github.com/hubblec4/Matroska-Playback/blob/master/src/Rotate.md

**Comment by robUx4** [comment]
Closing as RFC9559 has been published. The examples are not maintained here.
