### ISSUE TITLE
Remove ACM mapping from the codec mapping specs.

### ISSUE THREAD

**Issue by robUx4** [ietf-wg-cellar/matroska-specification#93]
We need to define the mapping from the original codec, not some other framework.

**Comment by dericed** [comment]
Do you mean the `A_MS/ACM` Codec Mapping or the little phrases such as `Corresponding ACM wFormatTag : 0x0055`?

**Comment by mbunkus** [comment]
I'm 99% sure Steve means the former: removing `A_MS/ACM`. However, there are files in the wild that use this (I think ffmpeg can create such files). mkvmerge doesn't support it, neither does mkvextract.

**Comment by dericed** [comment]
In the last survey I did of archive.org, there were at least 25 ACM files.

**Comment by mbunkus** [comment]
I know. Therefore I'd prefer including but deprecating the ID.

**Comment by dericed** [comment]
for reference here are a set of sample files using the Codec ID:

```
http://www.archive.org/download/Arabasma.OnePiece351/arabasma.One%20Piece%20-%20357%20-%20.mkv
http://www.archive.org/download/Arabasma.OnePiece351/arabasma.One%20Piece%20-%20358%20-%20.mkv
http://www.archive.org/download/Arabasma.OnePiece351/arabasma.One%20Piece%20-%20359%20-%20.mkv
http://www.archive.org/download/DPRK-KCTV-2013-08-13/DPRK-KCTV-2013-08-13.mkv
http://www.archive.org/download/FasleBahar1393Doostiha.IR2/Fasle_Bahar_1393_(Doostiha.IR)_2.mkv
http://www.archive.org/download/OP08-Shashah.tv/OP357_Shashah-tv.mkv
http://www.archive.org/download/OP08-Shashah.tv/OP358_Shashah-tv.mkv
http://www.archive.org/download/OP08-Shashah.tv/OP359_Shashah-tv.mkv
http://www.archive.org/download/op301-400ByMetalghost/One_Piece_357_metalghost_3asq.com.mkv
http://www.archive.org/download/op301-400ByMetalghost/One_Piece_358_metalghost_3asq.com.mkv
http://www.archive.org/download/op301-400ByMetalghost/One_Piece_359_metalghost_3asq.com.mkv
http://www.archive.org/download/O_P_All/OnePiece-357-.mkv
http://www.archive.org/download/O_P_All/OnePiece-358-.mkv
http://www.archive.org/download/O_P_All/OnePiece-359-.mkv
http://www.archive.org/download/OnePiece-ITALIAN/One%20Piece%20-%20357%20-%20.mkv
http://www.archive.org/download/OnePiece-ITALIAN/One%20Piece%20-%20358%20-%20.mkv
http://www.archive.org/download/OnePiece-ITALIAN/One%20Piece%20-%20359%20-%20.mkv
http://www.archive.org/download/TISEER2_HOTMAIL_MZ/Mazinger%20Z%20-%2000%20Arabic%20BD%20HARHOUR.mkv
http://www.archive.org/download/Clippy_Goes_To_Hell/Clippy_Goes_To_Hell.MKV
http://www.archive.org/download/Conan201202ActionLove/Conan%20-%20267%20-%20Action%20Love.mkv
http://www.archive.org/download/Conan201202ActionLove/Conan%20-%20268%20-%20Action%20Love.mkv
http://www.archive.org/download/mistressmovie2012/mistress.mkv
http://www.archive.org/download/salafia-73/Men_Aglak_13-Ramadan-1433.mkv
http://www.archive.org/download/Shaov.s.Topallerom/Shaov.i.Topaller.mkv
http://www.archive.org/download/WC14IvVsJap/ivorycoast-japan.1st.mkv
http://www.archive.org/download/WC14IvVsJap/ivorycoast-japan.2nd.mkv
http://www.archive.org/download/WC14UruVsCost/FIFA.World.Cup.2014.Uruguay.Vs.Costa.Rica.SDTV-WDTeam_1st.mkv
http://www.archive.org/download/WC14UruVsCost/FIFA.World.Cup.2014.Uruguay.Vs.Costa.Rica.SDTV-WDTeam_2nd.mkv
```

**Comment by ablwr** [comment]
I'm going to download "Clippy_Goes_To_Hell.MKV"

**Comment by dericed** [comment]
lol watching it now. It uses mp3 audio.

**Comment by ablwr** [comment]
Clippy experiences a LOT of violence in this piece of cinema, but he really is a sympathetic character, unlike the Clippy I once knew...

"Get a real operating system, like Linux" is a pretty good ending.

**Comment by JeromeMartinez** [comment]
IMO there is a pair: `V_MS/VFW/FOURCC` and `A_MS/ACM`.
None or both should be removed/deprecated at the same time, because they do the same thing (compatibility layer with AVI).
I have a bunch of files with `A_MS/ACM` in my private repository (mostly WMA2). 
For `V_MS/VFW/FOURCC`, files are also old (VC-1, DX50, XVID, VP62...) except for FFV1 but we already mapped FFV1 to native Codec mapping `V_FFV1` and FFmpeg is expected to switch to it next year (transition period).

I am for deprecating them, without removing them from the spec, as we need to inform people reading specs in order to understand a MKV file that it was supported at some point in the past.
I suggest to keep them in specs with a "SHOULD NOT" wording (deprecated, should not be used, for both).

**Comment by mbunkus** [comment]
I'd be fine with that.

**Comment by dericed** [comment]
Agreed, but perhaps the order should be:
1. add codec mappings for the V_MS/VFW/FOURCC and A_MS/ACM encodings in use (I can survey archive.org's collection for this)
2. deprecate V_MS/VFW/FOURCC and A_MS/ACM

If 2 is done first, then suddenly Matroska drops support for a lot of encodings, which is a bit agreessive.

**Comment by JeromeMartinez** [comment]
> I can survey archive.org's collection for this

I think we'll miss a mapping use in a corner of the Internet.
So new suggestion: not using the word "deprecated", just "SHOULD NOT" (= "there may exist valid reasons in particular circumstances", looks like it is the case), with and example "for old formats not having a direct mapping to Matroska codecs but having a mapping in AVI".
I don't think it is worth it to map old codecs to Matroska CodecIDs, as nearly no one uses this formats nowadays.
